begin;

drop schema if exists esa cascade;
create schema esa;

alter schema esa OWNER to megdb_admin;
set search_path = esa, public, pg_catalog;
set default_tablespace = '';
set default_with_oids = false;


drop  table if exists samples;
create table samples(
	id text not null, -- sample id
	taken timestamp with time zone not null, -- datetime the sample was taken on
	modified timestamp with time zone not null, -- datetime when the sample was modified
	collector_id text not null, -- who created the sample, user.login would fit most in here, but no restrictions for now...
	label text not null, -- sample label
	raw_data text not null, -- JSON data of the sample
	
	-- we're starting the general properties here...
	barcode text,
	project_id text,
	user_name text,
	ship_name text,
	nationality text,
	-- time is mapped with `taken`
	elevation decimal default 0,
	biome text,
	feature text,
	collection text,
	permit text,
	sampling_depth decimal default 0,
	water_depth decimal default 0,
	sample_size int default 0,
	weather_condition text,
	air_temperature decimal default 0,
	water_temperature decimal default 0,
	conductivity text,
	wind_speed decimal default 0,
	salinity decimal default 0,
	comment text,
--	geom geometry(Point, 4326),
	accuracy decimal default 0,
	
	constraint pk_samples primary key (id)
);
select AddGeometryColumn('esa','samples','geom',4326, 'POINT',2);


drop table if exists sample_images;
create table sample_images(
	uuid text not null,
	sid text not null, -- sample id
	data bytea, -- the image data
	path text, -- path to the image
	mime_type text, -- the MIME type
	
	constraint pk_sample_images primary key (uuid),
	constraint fk_sample_images_samples foreign key (sid)
			references samples(id) on update cascade
								 on delete cascade
);

drop table if exists gen_config;
create table gen_config(
	category text not null,
	name text not null,
	value text,
	
	constraint pk_gen_config primary key (category, name)
);

-- Configuration data dump
insert into gen_config
	(category, name, value)
values

--Features
('features', 'geographic feature', 'Geographic feature'),
('features', 'bedding-plane cave', 'Bedding-plane cave'),
('features', 'anthropogenic feature', 'Anthropogenic feature'),
('features', 'mine tailing', 'Mine tailing'),
('features', 'administrative region', 'Administrative region'),
('features', 'first-order administrative region', 'First-order administrative region'),
('features', 'second-order administrative region', 'Second-order administrative region'),
('features', 'third-order administrative region', 'Third-order administrative region'),
('features', 'fourth-order administrative region', 'Fourth-order administrative region'),
('features', 'national geopolitical entity', 'National geopolitical entity'),
('features', 'transport feature', 'Transport feature'),
('features', 'garden', 'Garden'),
('features', 'hydrographic feature', 'Hydrographic feature'),
('features', 'cave system', 'Cave system'),
('features', 'canal', 'Canal'),
('features', 'ocean', 'Ocean'),
('features', 'sea', 'Sea'),
('features', 'saline hydrographic feature', 'Saline hydrographic feature'),
('features', 'dry river', 'Dry river'),
('features', 'saline lake', 'Saline lake'),
('features', 'lake', 'Lake'),
('features', 'freshwater lake', 'Freshwater lake'),
('features', 'river', 'River'),
('features', 'stream', 'Stream'),
('features', 'intermittent stream', 'Intermittent stream'),
('features', 'reservoir', 'Reservoir'),
('features', 'well', 'Well'),
('features', 'spring', 'Spring'),
('features', 'sand pit', 'Sand pit'),
('features', 'watercourse', 'Watercourse'),
('features', 'dead cave', 'Dead cave'),
('features', 'wadi', 'Wadi'),
('features', 'bay', 'Bay'),
('features', 'pond', 'Pond'),
('features', 'rapids', 'Rapids'),
('features', 'marsh', 'Marsh'),
('features', 'irrigation canal', 'Irrigation canal'),
('features', 'ditch', 'Ditch'),
('features', 'lagoon', 'Lagoon'),
('features', 'fjord', 'Fjord'),
('features', 'waterfall', 'Waterfall'),
('features', 'tidal creek', 'Tidal creek'),
('features', 'drainage canal', 'Drainage canal'),
('features', 'wetland', 'Wetland'),
('features', 'peatland', 'Peatland'),
('features', 'estuary', 'Estuary'),
('features', 'hedge', 'Hedge'),
('features', 'canopy', 'Canopy'),
('features', 'navigation canal', 'Navigation canal'),
('features', 'volcanic hydrographic feature', 'Volcanic hydrographic feature'),
('features', 'geyser', 'Geyser'),
('features', 'hot spring', 'Hot spring'),
('features', 'crater lake', 'Crater lake'),
('features', 'freshwater marsh', 'Freshwater marsh'),
('features', 'saline marsh', 'Saline marsh'),
('features', 'saline evaporation pond', 'Saline evaporation pond'),
('features', 'fishpond', 'Fishpond'),
('features', 'mangrove swamp', 'Mangrove swamp'),
('features', 'underground lake', 'Underground lake'),
('features', 'underground river', 'Underground river'),
('features', 'underground stream', 'Underground stream'),
('features', 'underground water body', 'Underground water body'),
('features', 'populated place', 'Populated place'),
('features', 'water body', 'Water body'),
('features', 'road', 'Road'),
('features', 'railway', 'Railway'),
('features', 'man-made tunnel', 'Man-made tunnel'),
('features', 'cave', 'Cave'),
('features', 'tunnel', 'Tunnel'),
('features', 'distributary', 'Distributary'),
('features', 'constructed feature', 'Constructed feature'),
('features', 'fault cave', 'Fault cave'),
('features', 'aquaduct', 'Aquaduct'),
('features', 'building', 'Building'),
('features', 'dam', 'Dam'),
('features', 'bridge', 'Bridge'),
('features', 'mine', 'Mine'),
('features', 'agricultural feature', 'Agricultural feature'),
('features', 'farm', 'Farm'),
('features', 'flume', 'Flume'),
('features', 'mountain range', 'Mountain range'),
('features', 'mountain', 'Mountain'),
('features', 'hill range', 'Hill range'),
('features', 'hill', 'Hill'),
('features', 'mountain pass', 'Mountain pass'),
('features', 'alpine glacier', 'Alpine glacier'),
('features', 'plain', 'Plain'),
('features', 'cliff', 'Cliff'),
('features', 'sea cliff', 'Sea cliff'),
('features', 'inland cliff', 'Inland cliff'),
('features', 'coastal plain', 'Coastal plain'),
('features', 'beach', 'Beach'),
('features', 'sea beach', 'Sea beach'),
('features', 'lacustrine beach', 'Lacustrine beach'),
('features', 'volcanic feature', 'Volcanic feature'),
('features', 'lava field', 'Lava field'),
('features', 'caldera', 'Caldera'),
('features', 'desert', 'Desert'),
('features', 'island', 'Island'),
('features', 'artificial island', 'Artificial island'),
('features', 'valley', 'Valley'),
('features', 'delta', 'Delta'),
('features', 'cave entrance', 'Cave entrance'),
('features', 'mangrove island', 'Mangrove island'),
('features', 'undersea feature', 'Undersea feature'),
('features', 'lake surface', 'Lake surface'),
('features', 'grassland', 'Grassland'),
('features', 'heath', 'Heath'),
('features', 'meadow', 'Meadow'),
('features', 'woodland', 'Woodland'),
('features', 'lava tunnel', 'Lava tunnel'),
('features', 'forest', 'Forest'),
('features', 'tundra', 'Tundra'),
('features', 'cultivated habitat', 'Cultivated habitat'),
('features', 'field', 'Field'),
('features', 'orchard', 'Orchard'),
('features', 'vineyard', 'Vineyard'),
('features', 'plantation', 'Plantation'),
('features', 'coconut plantation', 'Coconut plantation'),
('features', 'planted forest', 'Planted forest'),
('features', 'oil palm plantation', 'Oil palm plantation'),
('features', 'artificial channel', 'Artificial channel'),
('features', 'track', 'Track'),
('features', 'political entity', 'Political entity'),
('features', 'supranational geopolitical entity', 'Supranational geopolitical entity'),
('features', 'mineral spring', 'Mineral spring'),
('features', 'sulfur spring', 'Sulfur spring'),
('features', 'badland', 'Badland'),
('features', 'dry valley', 'Dry valley'),
('features', 'stream valley', 'Stream valley'),
('features', 'reef', 'Reef'),
('features', 'glacial feature', 'Glacial feature'),
('features', 'ice sheet', 'Ice sheet'),
('features', 'glacier', 'Glacier'),
('features', 'permafrost', 'Permafrost'),
('features', 'buffer zone', 'Buffer zone'),
('features', 'demilitiarized zone', 'Demilitiarized zone'),
('features', 'coastal inlet', 'Coastal inlet'),
('features', 'cove', 'Cove'),
('features', 'irrigation ditch', 'Irrigation ditch'),
('features', 'drainage ditch', 'Drainage ditch'),
('features', 'bank', 'Bank'),
('features', 'stream bank', 'Stream bank'),
('features', 'river bank', 'River bank'),
('features', 'aquatic habitat', 'Aquatic habitat'),
('features', 'ice cap', 'Ice cap'),
('features', 'snow field', 'Snow field'),
('features', 'ocean current', 'Ocean current'),
('features', 'riffle', 'Riffle'),
('features', 'artificial reef', 'Artificial reef'),
('features', 'coral reef', 'Coral reef'),
('features', 'sabkha', 'Sabkha'),
('features', 'anabranch', 'Anabranch'),
('features', 'headwater', 'Headwater'),
('features', 'flood meadow', 'Flood meadow'),
('features', 'cirque', 'Cirque'),
('features', 'desert oasis', 'Desert oasis'),
('features', 'peat cut', 'Peat cut'),
('features', 'causeway', 'Causeway'),
('features', 'sugar plantation', 'Sugar plantation'),
('features', 'sisal plantation', 'Sisal plantation'),
('features', 'banana plantation', 'Banana plantation'),
('features', 'tea plantation', 'Tea plantation'),
('features', 'coffee plantation', 'Coffee plantation'),
('features', 'rubber plantation', 'Rubber plantation'),
('features', 'asphalt lake', 'Asphalt lake'),
('features', 'atoll', 'Atoll'),
('features', 'bar', 'Bar'),
('features', 'blowhole', 'Blowhole'),
('features', 'canyon', 'Canyon'),
('features', 'dune', 'Dune'),
('features', 'river valley', 'River valley'),
('features', 'sandy desert', 'Sandy desert'),
('features', 'rocky desert', 'Rocky desert'),
('features', 'isthmus', 'Isthmus'),
('features', 'karst', 'Karst'),
('features', 'elevation', 'Elevation'),
('features', 'moraine', 'Moraine'),
('features', 'levee', 'Levee'),
('features', 'mesa', 'Mesa'),
('features', 'mound', 'Mound'),
('features', 'nunatak', 'Nunatak'),
('features', 'plateau', 'Plateau'),
('features', 'stony desert', 'Stony desert'),
('features', 'hanging valley', 'Hanging valley'),
('features', 'raised mire', 'Raised mire'),
('features', 'string mire', 'String mire'),
('features', 'tundra mire', 'Tundra mire'),
('features', 'paisa mire', 'Paisa mire'),
('features', 'peat swamp', 'Peat swamp'),
('features', 'abyssal feature', 'Abyssal feature'),
('features', 'physiographic feature', 'Physiographic feature'),
('features', 'mudflat', 'Mudflat'),
('features', 'olive grove', 'Olive grove'),
('features', 'scree', 'Scree'),
('features', 'sinkhole', 'Sinkhole'),
('features', 'alkaline flat', 'Alkaline flat'),
('features', 'endorheic lake', 'Endorheic lake'),
('features', 'subglacial lake', 'Subglacial lake'),
('features', 'meromictoc lake', 'Meromictoc lake'),
('features', 'periglacial lake', 'Periglacial lake'),
('features', 'fjord lake', 'Fjord lake'),
('features', 'oxbow lake', 'Oxbow lake'),
('features', 'rift lake', 'Rift lake'),
('features', 'ephemeral spring', 'Ephemeral spring'),
('features', 'permanent spring', 'Permanent spring'),
('features', 'neritic zone', 'Neritic zone'),
('features', 'oceanic zone', 'Oceanic zone'),
('features', 'pelagic zone', 'Pelagic zone'),
('features', 'photic zone', 'Photic zone'),
('features', 'aphotic zone', 'Aphotic zone'),
('features', 'bathypelagic zone', 'Bathypelagic zone'),
('features', 'abyssalpelagic zone', 'Abyssalpelagic zone'),
('features', 'mesopelagic zone', 'Mesopelagic zone'),
('features', 'hadalpelagic zone', 'Hadalpelagic zone'),
('features', 'hydrothermal vent', 'Hydrothermal vent'),
('features', 'fumarole', 'Fumarole'),
('features', 'solfatara', 'Solfatara'),
('features', 'black smoker', 'Black smoker'),
('features', 'landlocked sea', 'Landlocked sea'),
('features', 'archipelago', 'Archipelago'),
('features', 'continental island', 'Continental island'),
('features', 'oceanic island', 'Oceanic island'),
('features', 'continental shelf', 'Continental shelf'),
('features', 'slightly stratified estuary', 'Slightly stratified estuary'),
('features', 'highly stratified estuary', 'Highly stratified estuary'),
('features', 'saline wedge estuary', 'Saline wedge estuary'),
('features', 'vertically mixed estuary', 'Vertically mixed estuary'),
('features', 'inverse estuary', 'Inverse estuary'),
('features', 'intermittent estuary', 'Intermittent estuary'),
('features', 'coastal wetland', 'Coastal wetland'),
('features', 'moor', 'Moor'),
('features', 'fen', 'Fen'),
('features', 'swamp', 'Swamp'),
('features', 'bayou', 'Bayou'),
('features', 'carr', 'Carr'),
('features', 'dambo', 'Dambo'),
('features', 'hydromorphic/phreatic dambo', 'Hydromorphic/phreatic dambo'),
('features', 'fluvial dambo', 'Fluvial dambo'),
('features', 'pocasin', 'Pocasin'),
('features', 'saline wetland', 'Saline wetland'),
('features', 'tidal mudflat', 'Tidal mudflat'),
('features', 'lacustrine mudflat', 'Lacustrine mudflat'),
('features', 'freshwater wetland', 'Freshwater wetland'),
('features', 'abyssal plain', 'Abyssal plain'),
('features', 'maar', 'Maar'),
('features', 'volcanic crater', 'Volcanic crater'),
('features', 'volcano', 'Volcano'),
('features', 'glacial valley', 'Glacial valley'),
('features', 'lateral moraine', 'Lateral moraine'),
('features', 'medial moraine', 'Medial moraine'),
('features', 'ground moraine', 'Ground moraine'),
('features', 'terminal moraine', 'Terminal moraine'),
('features', 'scroll plane', 'Scroll plane'),
('features', 'till plan', 'Till plan'),
('features', 'flood plain', 'Flood plain'),
('features', 'floodway', 'Floodway'),
('features', 'flood fringe', 'Flood fringe'),
('features', 'alluvial plain', 'Alluvial plain'),
('features', 'lacustrine plain', 'Lacustrine plain'),
('features', 'prairie', 'Prairie'),
('features', 'savanna', 'Savanna'),
('features', 'steppe', 'Steppe'),
('features', 'fissure cave', 'Fissure cave'),
('features', 'seamount', 'Seamount'),
('features', 'guyot', 'Guyot'),
('features', 'pasture', 'Pasture'),
('features', 'submarine canyon', 'Submarine canyon'),
('features', 'lake bed', 'Lake bed'),
('features', 'land-tied island', 'Land-tied island'),
('features', 'beaver pond', 'Beaver pond'),
('features', 'chott', 'Chott'),
('features', 'confluence', 'Confluence'),
('features', 'continental slope', 'Continental slope'),
('features', 'continental rise', 'Continental rise'),
('features', 'ocean trench', 'Ocean trench'),
('features', 'drumlin', 'Drumlin'),
('features', 'dry lake', 'Dry lake'),
('features', 'dry stream', 'Dry stream'),
('features', 'saline pan', 'Saline pan'),
('features', 'escarpment', 'Escarpment'),
('features', 'fault escarpment', 'Fault escarpment'),
('features', 'esker', 'Esker'),
('features', 'ridge', 'Ridge'),
('features', 'quarry', 'Quarry'),
('features', 'quicksand area', 'Quicksand area'),
('features', 'polder', 'Polder'),
('features', 'butte', 'Butte'),
('features', 'cotton plantation', 'Cotton plantation'),
('features', 'horst', 'Horst'),
('features', 'graben', 'Graben'),
('features', 'drainage basin', 'Drainage basin'),
('features', 'watershed', 'Watershed'),
('features', 'continental divide', 'Continental divide'),
('features', 'fish farm', 'Fish farm'),
('features', 'fish hatchery', 'Fish hatchery'),
('features', 'rice field', 'Rice field'),
('features', 'paddy field', 'Paddy field'),
('features', 'iceberg', 'Iceberg'),
('features', 'ice mass', 'Ice mass'),
('features', 'scrubland', 'Scrubland'),
('features', 'chaparal', 'Chaparal'),
('features', 'rift valley', 'Rift valley'),
('features', 'coast', 'Coast'),
('features', 'shore', 'Shore'),
('features', 'peninsula', 'Peninsula'),
('features', 'spit', 'Spit'),
('features', 'icefall', 'Icefall'),
('features', 'dune slack', 'Dune slack'),
('features', 'depression', 'Depression'),
('features', 'impact crater', 'Impact crater'),
('features', 'kettle', 'Kettle'),
('features', 'sandur', 'Sandur'),
('features', 'blowout', 'Blowout'),
('features', 'alluvial fan', 'Alluvial fan'),
('features', 'bajada', 'Bajada'),
('features', 'intertidal zone', 'Intertidal zone'),
('features', 'tidal pool', 'Tidal pool'),
('features', 'high tide zone', 'High tide zone'),
('features', 'low tide zone', 'Low tide zone'),
('features', 'crevasse', 'Crevasse'),
('features', 'joint-plane cave', 'Joint-plane cave'),
('features', 'lava cave', 'Lava cave'),
('features', 'live cave', 'Live cave'),
('features', 'outflow cave', 'Outflow cave'),
('features', 'polje', 'Polje'),
('features', 'sea cave', 'Sea cave'),
('features', 'speleothem', 'Speleothem'),
('features', 'vadoze zone', 'Vadoze zone'),
('features', 'phreatic zone', 'Phreatic zone'),
('features', 'stalagmite', 'Stalagmite'),
('features', 'stalactite', 'Stalactite'),
('features', 'doline', 'Doline'),
('features', 'subjacent karst', 'Subjacent karst'),
('features', 'syngenetic karst', 'Syngenetic karst'),
('features', 'polygonal karst', 'Polygonal karst'),
('features', 'doline karst', 'Doline karst'),
('features', 'orange juice', 'Orange juice'),
('features', 'vomit', 'Vomit'),
('features', 'piece of rock', 'Piece of rock'),
('features', 'grain of sand', 'Grain of sand'),
('features', 'piece of gravel', 'Piece of gravel'),
('features', 'ice cap dome', 'Ice cap dome'),
('features', 'particle of silt', 'Particle of silt'),
('features', 'grain of desert sand', 'Grain of desert sand'),
('features', 'grain of beach sand', 'Grain of beach sand'),
('features', 'grain of acid dune sand', 'Grain of acid dune sand'),
('features', 'grain of sea sand', 'Grain of sea sand'),
('features', 'grain of rocky sand', 'Grain of rocky sand'),
('features', 'terrarium', 'Terrarium'),
('features', 'somma volcano', 'Somma volcano'),
('features', 'volcanic arc', 'Volcanic arc'),
('features', 'continental arc', 'Continental arc'),
('features', 'island arc', 'Island arc'),
('features', 'volcanic field', 'Volcanic field'),
('features', 'monogenetic volcanic field', 'Monogenetic volcanic field'),
('features', 'pyroclastic cone', 'Pyroclastic cone'),
('features', 'lock', 'Lock'),
('features', 'protected area', 'Protected area'),
('features', 'natural monument', 'Natural monument'),
('features', 'national forest', 'National forest'),
('features', 'site of special scientific interest', 'Site of special scientific interest'),
('features', 'marine park', 'Marine park'),
('features', 'nature reserve', 'Nature reserve'),
('features', 'national wildlife refuge', 'National wildlife refuge'),
('features', 'ramsar site', 'Ramsar site'),
('features', 'national nature reserve', 'National nature reserve'),
('features', 'national park', 'National park'),
('features', 'ephemeral island', 'Ephemeral island'),
('features', 'brine pool', 'Brine pool'),
('features', 'tuya', 'Tuya'),
('features', 'complex volcano', 'Complex volcano'),
('features', 'pyroclastic shield volcano', 'Pyroclastic shield volcano'),
('features', 'geothermal field', 'Geothermal field'),
('features', 'wildlife management area', 'Wildlife management area'),
('features', 'world heritage site', 'World heritage site'),
('features', 'biosphere reserve', 'Biosphere reserve'),
('features', 'artificial lake', 'Artificial lake'),
('features', 'canal head reservoir', 'Canal head reservoir'),
('features', 'ice shelf', 'Ice shelf'),
('features', 'massif', 'Massif'),
('features', 'lake shore', 'Lake shore'),
('features', 'stream bed', 'Stream bed'),
('features', 'river bed', 'River bed'),
('features', 'stream mouth', 'Stream mouth'),
('features', 'river mouth', 'River mouth'),
('features', 'intermittent lake', 'Intermittent lake'),
('features', 'intermittent watercourse', 'Intermittent watercourse'),
('features', 'intermittent wetland', 'Intermittent wetland'),
('features', 'mountain spur', 'Mountain spur'),
('features', 'land bridge', 'Land bridge'),
('features', 'ice tongue', 'Ice tongue'),
('features', 'sound', 'Sound'),
('features', 'strait', 'Strait'),
('features', 'channel', 'Channel'),
('features', 'marine channel', 'Marine channel'),
('features', 'lake channel', 'Lake channel'),
('features', 'volcanic cone', 'Volcanic cone'),
('features', 'ash cone', 'Ash cone'),
('features', 'cinder cone', 'Cinder cone'),
('features', 'spatter cone', 'Spatter cone'),
('features', 'mud volcano', 'Mud volcano'),
('features', 'shield volcano', 'Shield volcano'),
('features', 'stratovolcano', 'Stratovolcano'),
('features', 'submarine volcano', 'Submarine volcano'),
('features', 'mid-ocean ridge', 'Mid-ocean ridge'),
('features', 'subglacial volcano', 'Subglacial volcano'),
('features', 'volcanic fissure', 'Volcanic fissure'),
('features', 'whirlpool', 'Whirlpool'),
('features', 'kipuka', 'Kipuka'),
('features', 'ford', 'Ford'),
('features', 'tidal watercourse', 'Tidal watercourse'),
('features', 'pingo', 'Pingo'),
('features', 'natural arch', 'Natural arch'),
('features', 'raised beach', 'Raised beach'),
('features', 'coastal dune', 'Coastal dune'),
('features', 'machair', 'Machair'),
('features', 'ria', 'Ria'),
('features', 'stack', 'Stack'),
('features', 'tombolo', 'Tombolo'),
('features', 'wave-cut platform', 'Wave-cut platform'),
('features', 'limestone pavement', 'Limestone pavement'),
('features', 'river island', 'River island'),
('features', 'lake island', 'Lake island'),
('features', 'cold seep', 'Cold seep'),
('features', 'ocean floor', 'Ocean floor'),
('features', 'meander', 'Meander'),
('features', 'biome', 'Biome'),
('features', 'arete', 'Arete'),
('features', 'dirt cone', 'Dirt cone'),
('features', 'drumlin field', 'Drumlin field'),
('features', 'monadnock', 'Monadnock'),
('features', 'kame terrace', 'Kame terrace'),
('features', 'outwash fan', 'Outwash fan'),
('features', 'proglacial lake', 'Proglacial lake'),
('features', 'tunnel valley', 'Tunnel valley'),
('features', 'Nye channel', 'Nye channel'),
('features', 'alas', 'Alas'),
('features', 'dell', 'Dell'),
('features', 'rock shelter', 'Rock shelter'),
('features', 'terracette', 'Terracette'),
('features', 'maelstrom', 'Maelstrom'),
('features', 'flood control reservoir', 'Flood control reservoir'),
('features', 'clearing', 'Clearing'),
('features', 'transvasement', 'Transvasement'),
('features', 'terrestrial biome', 'Terrestrial biome'),
('features', 'marine biome', 'Marine biome'),
('features', 'hydroelectric reservoir', 'Hydroelectric reservoir'),
('features', 'drinking water reservoir', 'Drinking water reservoir'),
('features', 'irrigation reservoir', 'Irrigation reservoir'),
('features', 'amenity lake', 'Amenity lake'),
('features', 'ribbon lake', 'Ribbon lake'),
('features', 'liman', 'Liman'),
('features', 'turlough', 'Turlough'),
('features', 'tarn', 'Tarn'),
('features', 'tidewater glacier', 'Tidewater glacier'),
('features', 'plateau glacier', 'Plateau glacier'),
('features', 'valley glacier', 'Valley glacier'),
('features', 'outlet glacier', 'Outlet glacier'),
('features', 'penplain', 'Penplain'),
('features', 'pseudocrater', 'Pseudocrater'),
('features', 'polygenetic volcanic field', 'Polygenetic volcanic field'),
('features', 'harbor', 'Harbor'),
('features', 'artificial harbor', 'Artificial harbor'),
('features', 'natural harbor', 'Natural harbor'),
('features', 'marine hydrographic feature', 'Marine hydrographic feature'),
('features', 'university campus', 'University campus'),
('features', 'hydroelectric dam', 'Hydroelectric dam'),
('features', 'research facility', 'Research facility'),
('features', 'irrigation dam', 'Irrigation dam'),
('features', 'flood control dam', 'Flood control dam'),
('features', 'backwater', 'Backwater'),
('features', 'gravel pit', 'Gravel pit'),
('features', 'cut', 'Cut'),
('features', 'inlet', 'Inlet'),
('features', 'lake inlet', 'Lake inlet'),
('features', 'mount', 'Mount'),
('features', 'range of mounts', 'Range of mounts'),
('features', 'mouth', 'Mouth'),
('features', 'peak', 'Peak'),
('features', 'pinnacle', 'Pinnacle'),
('features', 'sea floor', 'Sea floor'),
('features', 'plunge pool', 'Plunge pool'),
('features', 'polynya', 'Polynya'),
('features', 'sea shore', 'Sea shore'),
('features', 'shoreline', 'Shoreline'),
('features', 'paternoster lake', 'Paternoster lake'),
('features', 'glacial lake', 'Glacial lake'),
('features', 'palsa', 'Palsa'),
('features', 'consequent stream', 'Consequent stream'),
('features', 'subsequent stream', 'Subsequent stream'),
('features', 'resequent stream', 'Resequent stream'),
('features', 'obsequent stream', 'Obsequent stream'),
('features', 'insequent stream', 'Insequent stream'),
('features', 'tributary', 'Tributary'),
('features', 'rill', 'Rill'),
('features', 'rincon', 'Rincon'),
('features', 'volcanic dike', 'Volcanic dike'),
('features', 'trough', 'Trough'),
('features', 'beaver dam', 'Beaver dam'),
('features', 'bed', 'Bed'),
('features', 'intermittent saline lake', 'Intermittent saline lake'),
('features', 'intermittent oxbow lake', 'Intermittent oxbow lake'),
('features', 'intermittent pond', 'Intermittent pond'),
('features', 'underground irrigation canal', 'Underground irrigation canal'),
('features', 'intermittent reservoir', 'Intermittent reservoir'),
('features', 'wadi mouth', 'Wadi mouth'),
('features', 'terrace', 'Terrace'),
('features', 'marine terrace', 'Marine terrace'),
('features', 'meander neck', 'Meander neck'),
('features', 'blanket bog', 'Blanket bog'),
('features', 'pond bed', 'Pond bed'),
('features', 'reservoir bed', 'Reservoir bed'),
('features', 'crater', 'Crater'),
('features', 'road cut', 'Road cut'),
('features', 'hammock', 'Hammock'),
('features', 'lost stream', 'Lost stream'),
('features', 'ditch mouth', 'Ditch mouth'),
('features', 'agricultural terrace', 'Agricultural terrace'),
('features', 'landslide', 'Landslide'),
('features', 'rockfall', 'Rockfall'),
('features', 'canal tunnel', 'Canal tunnel'),
('features', 'cutoff', 'Cutoff'),
('features', 'abandoned watercourse', 'Abandoned watercourse'),
('features', 'canalized stream', 'Canalized stream'),
('features', 'cleft', 'Cleft'),
('features', 'interfluve', 'Interfluve'),
('features', 'ice cap ridge', 'Ice cap ridge'),
('features', 'beach ridge', 'Beach ridge'),
('features', 'apron', 'Apron'),
('features', 'ice cap depression', 'Ice cap depression'),
('features', 'intermittent saline evaporation pond', 'Intermittent saline evaporation pond'),
('features', 'landfill', 'Landfill'),
('features', 'pothole', 'Pothole'),
('features', 'weir', 'Weir'),
('features', 'moatan', 'Moatan'),
('features', 'boulder field', 'Boulder field'),
('features', 'arrugado', 'Arrugado'),
('features', 'sill', 'Sill'),
('features', 'brackish lake', 'Brackish lake'),
('features', 'brackish pond', 'Brackish pond'),
('features', 'kame', 'Kame'),
('features', 'swale', 'Swale'),
('features', 'leat', 'Leat'),
('features', 'shingle beach', 'Shingle beach'),
('features', 'lake sediment', 'Lake sediment'),
('features', 'waterhole', 'Waterhole'),
('features', 'gravel field', 'Gravel field'),
('features', 'intermittent water body', 'Intermittent water body'),
('features', 'range of seamounts', 'Range of seamounts'),
('features', 'endorheic basin', 'Endorheic basin'),
('features', 'talik', 'Talik'),
('features', 'multipurpose dam', 'Multipurpose dam'),
('features', 'saddle dam', 'Saddle dam'),
('features', 'check dam', 'Check dam'),
('features', 'wing dam', 'Wing dam'),
('features', 'dry dam', 'Dry dam'),
('features', 'diversionary dam', 'Diversionary dam'),
('features', 'weapons test site', 'Weapons test site'),
('features', 'nuclear weapons test site', 'Nuclear weapons test site'),
('features', 'military training area', 'Military training area'),
('features', 'park', 'Park'),
('features', 'pier', 'Pier'),
('features', 'archeological site', 'Archeological site'),
('features', 'sports facility', 'Sports facility'),
('features', 'winter sports facility', 'Winter sports facility'),
('features', 'calanque', 'Calanque'),
('features', 'aerial habitat', 'Aerial habitat'),
('features', 'marine habitat', 'Marine habitat'),
('features', 'brackish water habitat', 'Brackish water habitat'),
('features', 'arboreal habitat', 'Arboreal habitat'),
('features', 'subterrestrial habitat', 'Subterrestrial habitat'),
('features', 'city', 'City'),
('features', 'freshwater biome', 'Freshwater biome'),
('features', 'Tundra biome', 'Tundra biome'),
('features', 'Temperate coniferous forest biome', 'Temperate coniferous forest biome'),
('features', 'Temperate broadleaf and mixed forest biome', 'Temperate broadleaf and mixed forest biome'),
('features', 'Temperate grasslands, savannas, and shrubland biome', 'Temperate grasslands, savannas, and shrubland biome'),
('features', 'Mediterranean forests, woodlands, and shrub biome', 'Mediterranean forests, woodlands, and shrub biome'),
('features', 'Tropical and subtropical moist broadleaf forest biome', 'Tropical and subtropical moist broadleaf forest biome'),
('features', 'Tropical and subtropical dry broadleaf forest biome', 'Tropical and subtropical dry broadleaf forest biome'),
('features', 'Tropical and subtropical grasslands, savannas, and shrubland biome', 'Tropical and subtropical grasslands, savannas, and shrubland biome'),
('features', 'Montane grasslands and shrubland biome', 'Montane grasslands and shrubland biome'),
('features', 'Deserts and xeric shrubland biome', 'Deserts and xeric shrubland biome'),
('features', 'Mangrove biome', 'Mangrove biome'),
('features', 'Flooded grasslands and savanna biome', 'Flooded grasslands and savanna biome'),
('features', 'endolithic habitat', 'Endolithic habitat'),
('features', 'Large river biome', 'Large river biome'),
('features', 'Large river headwater biome', 'Large river headwater biome'),
('features', 'Large river delta biome', 'Large river delta biome'),
('features', 'Small river biome', 'Small river biome'),
('features', 'Large lake biome', 'Large lake biome'),
('features', 'Small lake biome', 'Small lake biome'),
('features', 'Xeric basin biome', 'Xeric basin biome'),
('features', 'Polar biome', 'Polar biome'),
('features', 'Temperate shelf and sea biome', 'Temperate shelf and sea biome'),
('features', 'Temperate upwelling biome', 'Temperate upwelling biome'),
('features', 'Tropical upwelling biome', 'Tropical upwelling biome'),
('features', 'Tropical coral biome', 'Tropical coral biome'),
('features', 'rock', 'Rock'),
('features', 'mine drainage', 'Mine drainage'),
('features', 'acid mine drainage', 'Acid mine drainage'),
('features', 'soil', 'Soil'),
('features', 'marine water body', 'Marine water body'),
('features', 'slope', 'Slope'),
('features', 'waste water', 'Waste water'),
('features', 'food product', 'Food product'),
('features', 'feces', 'Feces'),
('features', 'mesoscopic physical object', 'Mesoscopic physical object'),
('features', 'air', 'Air'),
('features', 'water', 'Water'),
('features', 'sediment', 'Sediment'),
('features', 'dust', 'Dust'),
('features', 'terrestrial habitat', 'Terrestrial habitat'),
('features', 'saline water', 'Saline water'),
('features', 'fresh water', 'Fresh water'),
('features', 'hypersaline water', 'Hypersaline water'),
('features', 'igneous rock', 'Igneous rock'),
('features', 'plutonic rock', 'Plutonic rock'),
('features', 'volcanic rock', 'Volcanic rock'),
('features', 'sedimentary rock', 'Sedimentary rock'),
('features', 'metamorphic rock', 'Metamorphic rock'),
('features', 'sewage', 'Sewage'),
('features', 'brackish water', 'Brackish water'),
('features', 'extreme habitat', 'Extreme habitat'),
('features', 'acid habitat', 'Acid habitat'),
('features', 'alkaline habitat', 'Alkaline habitat'),
('features', 'high pressure habitat', 'High pressure habitat'),
('features', 'haline habitat', 'Haline habitat'),
('features', 'high temperature habitat', 'High temperature habitat'),
('features', 'cold temperature habitat', 'Cold temperature habitat'),
('features', 'extreme high temperature habitat', 'Extreme high temperature habitat'),
('features', 'high osmolarity habitat', 'High osmolarity habitat'),
('features', 'extraterrestial habitat', 'Extraterrestial habitat'),
('features', 'aquatic biome', 'Aquatic biome'),
('features', 'anthropogenic habitat', 'Anthropogenic habitat'),
('features', 'organism-associated habitat', 'Organism-associated habitat'),
('features', 'carcass', 'Carcass'),
('features', 'biofilm', 'Biofilm'),
('features', 'meteorite', 'Meteorite'),
('features', 'habitat', 'Habitat'),
('features', 'freshwater habitat', 'Freshwater habitat'),
('features', 'WWF biome', 'WWF biome'),
('features', 'bone', 'Bone'),
('features', 'wood', 'Wood'),
('features', 'ground water', 'Ground water'),
('features', 'surface water', 'Surface water'),
('features', 'wastewater treatment plant', 'Wastewater treatment plant'),
('features', 'sludge', 'Sludge'),
('features', 'anaerobic sediment', 'Anaerobic sediment'),
('features', 'activated sludge', 'Activated sludge'),
('features', 'urine', 'Urine'),
('features', 'chondrite', 'Chondrite'),
('features', 'stony meteorite', 'Stony meteorite'),
('features', 'achondrite', 'Achondrite'),
('features', 'stony-iron meteorite', 'Stony-iron meteorite'),
('features', 'iron meteorite', 'Iron meteorite'),
('features', 'limestone', 'Limestone'),
('features', 'chalk', 'Chalk'),
('features', 'sandstone', 'Sandstone'),
('features', 'shale', 'Shale'),
('features', 'raw primary sludge', 'Raw primary sludge'),
('features', 'secondary sludge', 'Secondary sludge'),
('features', 'biosolids', 'Biosolids'),
('features', 'oil sludge', 'Oil sludge'),
('features', 'oil spill', 'Oil spill'),
('features', 'oil', 'Oil'),
('features', 'oil seep', 'Oil seep'),
('features', 'gold mine drainage', 'Gold mine drainage'),
('features', 'marine sediment', 'Marine sediment'),
('features', 'contaminated sediment', 'Contaminated sediment'),
('features', 'petroleum contaminated sediment', 'Petroleum contaminated sediment'),
('features', 'contaminated soil', 'Contaminated soil'),
('features', 'creosote contaminated soil', 'Creosote contaminated soil'),
('features', 'sea sand', 'Sea sand'),
('features', 'alkaline hot spring', 'Alkaline hot spring'),
('features', 'acid hot spring', 'Acid hot spring'),
('features', 'alkaline salt lake', 'Alkaline salt lake'),
('features', 'arsenic-rich mud', 'Arsenic-rich mud'),
('features', 'bioreactor', 'Bioreactor'),
('features', 'anaerobic bioreactor', 'Anaerobic bioreactor'),
('features', 'anaerobic dechlorinating bioreactor', 'Anaerobic dechlorinating bioreactor'),
('features', 'aerobic bioreactor', 'Aerobic bioreactor'),
('features', 'stream sediment', 'Stream sediment'),
('features', 'mesophilic sulfur spring', 'Mesophilic sulfur spring'),
('features', 'anaerobic sludge', 'Anaerobic sludge'),
('features', 'hypolimnion', 'Hypolimnion'),
('features', 'epilimnion', 'Epilimnion'),
('features', 'metalimnion', 'Metalimnion'),
('features', 'anaerobic mud', 'Anaerobic mud'),
('features', 'anaerobic stream sediment', 'Anaerobic stream sediment'),
('features', 'treated wood', 'Treated wood'),
('features', 'arsenate treated wood', 'Arsenate treated wood'),
('features', 'brackish estuary', 'Brackish estuary'),
('features', 'beach sand', 'Beach sand'),
('features', 'pebble', 'Pebble'),
('features', 'cobble', 'Cobble'),
('features', 'leachate', 'Leachate'),
('features', 'borax leachate', 'Borax leachate'),
('features', 'calcite hot spring', 'Calcite hot spring'),
('features', 'cave wall', 'Cave wall'),
('features', 'chromate contaminated soil', 'Chromate contaminated soil'),
('features', 'xylene contaminated soil', 'Xylene contaminated soil'),
('features', 'coal mine lake sediment', 'Coal mine lake sediment'),
('features', 'coarse beach sand', 'Coarse beach sand'),
('features', 'sea water', 'Sea water'),
('features', 'coastal water', 'Coastal water'),
('features', 'ocean water', 'Ocean water'),
('features', 'biofilter', 'Biofilter'),
('features', 'compost biofilter', 'Compost biofilter'),
('features', 'radioactive sediment', 'Radioactive sediment'),
('features', 'high-level radioactive sediment', 'High-level radioactive sediment'),
('features', 'Superfund Site', 'Superfund Site'),
('features', 'stromatolite mat', 'Stromatolite mat'),
('features', 'ditch water', 'Ditch water'),
('features', 'drilling bore water', 'Drilling bore water'),
('features', 'estuarine mud', 'Estuarine mud'),
('features', 'fermented agave juice', 'Fermented agave juice'),
('features', 'fermenting sugar cane juice', 'Fermenting sugar cane juice'),
('features', 'fermenting Elaeis Palm sap', 'Fermenting Elaeis Palm sap'),
('features', 'fossil', 'Fossil'),
('features', 'meat food product', 'Meat food product'),
('features', 'sausage', 'Sausage'),
('features', 'platinum mine', 'Platinum mine'),
('features', 'gold mine', 'Gold mine'),
('features', 'coal mine', 'Coal mine'),
('features', 'compost', 'Compost'),
('features', 'hay compost', 'Hay compost'),
('features', 'liver paste', 'Liver paste'),
('features', 'hospital', 'Hospital'),
('features', 'hot dog', 'Hot dog'),
('features', 'processed meat product', 'Processed meat product'),
('features', 'contaminated sludge', 'Contaminated sludge'),
('features', '1,4-dioxane contaminated sludge', '1,4-dioxane contaminated sludge'),
('features', 'iron-reducing zone of petroleum contaminated sediment', 'Iron-reducing zone of petroleum contaminated sediment'),
('features', 'intertidal sediment', 'Intertidal sediment'),
('features', 'naphthalene contaminated sediment', 'Naphthalene contaminated sediment'),
('features', 'neutral hot spring', 'Neutral hot spring'),
('features', 'nitrobenzene contaminated sediment', 'Nitrobenzene contaminated sediment'),
('features', 'oil tank', 'Oil tank'),
('features', 'underground physiographic feature', 'Underground physiographic feature'),
('features', 'oil reservoir', 'Oil reservoir'),
('features', 'contaminated water', 'Contaminated water'),
('features', 'milk formula', 'Milk formula'),
('features', 'powdered milk formula', 'Powdered milk formula'),
('features', 'cheese product', 'Cheese product'),
('features', 'yogurt', 'Yogurt'),
('features', 'animal litter', 'Animal litter'),
('features', 'poultry litter', 'Poultry litter'),
('features', 'pulp-bleaching waste water', 'Pulp-bleaching waste water'),
('features', 'oil field production water', 'Oil field production water'),
('features', 'pyritic acid mine drainage', 'Pyritic acid mine drainage'),
('features', 'aquarium', 'Aquarium'),
('features', 'saline water aquarium', 'Saline water aquarium'),
('features', 'fresh water aquarium', 'Fresh water aquarium'),
('features', 'sandy beach', 'Sandy beach'),
('features', 'sea ice', 'Sea ice'),
('features', 'cis-dichloroethane contaminated sediment', 'Cis-dichloroethane contaminated sediment'),
('features', 'organically contaminated sediment', 'Organically contaminated sediment'),
('features', 'inorganically contaminated sediment', 'Inorganically contaminated sediment'),
('features', 'contamination feature', 'Contamination feature'),
('features', 'unexploded-ordnance dump', 'Unexploded-ordnance dump'),
('features', 'coal mine waste', 'Coal mine waste'),
('features', 'self-heating coal mine waste', 'Self-heating coal mine waste'),
('features', 'saline lake sediment', 'Saline lake sediment'),
('features', 'sulfide-oxidizing bioreactor', 'Sulfide-oxidizing bioreactor'),
('features', 'thermophilic anaerobic methanogenic reactor', 'Thermophilic anaerobic methanogenic reactor'),
('features', 'thermophilic granular sludge', 'Thermophilic granular sludge'),
('features', 'anaerobic sludge blanket reactor', 'Anaerobic sludge blanket reactor'),
('features', 'power plant', 'Power plant'),
('features', 'geothermal power plant', 'Geothermal power plant'),
('features', 'plant food product', 'Plant food product'),
('features', 'cabbage product', 'Cabbage product'),
('features', 'commercial yogurt', 'Commercial yogurt'),
('features', 'cheese starter culture', 'Cheese starter culture'),
('features', 'cheese spoilage', 'Cheese spoilage'),
('features', 'shop', 'Shop'),
('features', 'food shop', 'Food shop'),
('features', 'oligotrophic water', 'Oligotrophic water'),
('features', 'eutrophic water', 'Eutrophic water'),
('features', 'mesotrophic water', 'Mesotrophic water'),
('features', 'borehole', 'Borehole'),
('features', 'saline water habitat', 'Saline water habitat'),
('features', 'pond water', 'Pond water'),
('features', 'arenosol', 'Arenosol'),
('features', 'anthrosol', 'Anthrosol'),
('features', 'alisol', 'Alisol'),
('features', 'andosol', 'Andosol'),
('features', 'albeluvisol', 'Albeluvisol'),
('features', 'acrisol', 'Acrisol'),
('features', 'cambisol', 'Cambisol'),
('features', 'cryosol', 'Cryosol'),
('features', 'chernozem', 'Chernozem'),
('features', 'durisol', 'Durisol'),
('features', 'calcisol', 'Calcisol'),
('features', 'kastanozem', 'Kastanozem'),
('features', 'leptosol', 'Leptosol'),
('features', 'lixisol', 'Lixisol'),
('features', 'histosol', 'Histosol'),
('features', 'gleysol', 'Gleysol'),
('features', 'gypsisol', 'Gypsisol'),
('features', 'ferralsol', 'Ferralsol'),
('features', 'nitisol', 'Nitisol'),
('features', 'luvisol', 'Luvisol'),
('features', 'phaeozem', 'Phaeozem'),
('features', 'plinthosol', 'Plinthosol'),
('features', 'planosol', 'Planosol'),
('features', 'solonchak', 'Solonchak'),
('features', 'umbrisol', 'Umbrisol'),
('features', 'vertisol', 'Vertisol'),
('features', 'solonetz', 'Solonetz'),
('features', 'regosol', 'Regosol'),
('features', 'podzol', 'Podzol'),
('features', 'loam', 'Loam'),
('features', 'agricultural soil', 'Agricultural soil'),
('features', 'dune soil', 'Dune soil'),
('features', 'forest soil', 'Forest soil'),
('features', 'clay soil', 'Clay soil'),
('features', 'garden soil', 'Garden soil'),
('features', 'waste', 'Waste'),
('features', 'agricultural waste', 'Agricultural waste'),
('features', 'chicken breeding waste', 'Chicken breeding waste'),
('features', 'industrial waste', 'Industrial waste'),
('features', 'sphagnum bog', 'Sphagnum bog'),
('features', 'thermocline', 'Thermocline'),
('features', 'chemocline', 'Chemocline'),
('features', 'nuclear power plant', 'Nuclear power plant'),
('features', 'waste treatment plant', 'Waste treatment plant'),
('features', 'fluvisol', 'Fluvisol'),
('features', 'stagnosol', 'Stagnosol'),
('features', 'technosol', 'Technosol'),
('features', 'animal waste', 'Animal waste'),
('features', 'back-arc basin', 'Back-arc basin'),
('features', 'environmental feature', 'Environmental feature'),
('features', 'ocean basin', 'Ocean basin'),
('features', 'hay', 'Hay'),
('features', 'abode soil', 'Abode soil'),
('features', 'alluvial soil', 'Alluvial soil'),
('features', 'bagasse', 'Bagasse'),
('features', 'organic waste', 'Organic waste'),
('features', 'air conditioning unit', 'Air conditioning unit'),
('features', 'oil contaminated soil', 'Oil contaminated soil'),
('features', 'warm seep', 'Warm seep'),
('features', 'clay', 'Clay'),
('features', 'fuel oil', 'Fuel oil'),
('features', 'petroleum', 'Petroleum'),
('features', 'Udvardy biome', 'Udvardy biome'),
('features', 'Evergreen sclerophyllous forests, scrub, or woodlands', 'Evergreen sclerophyllous forests, scrub, or woodlands'),
('features', 'Temperate grasslands', 'Temperate grasslands'),
('features', 'Temperate broad-leaf forests or woodlands and subpolar deciduous thickets', 'Temperate broad-leaf forests or woodlands and subpolar deciduous thickets'),
('features', 'Tropical dry or deciduous forests (including Monsoon forests) or woodlands', 'Tropical dry or deciduous forests (including Monsoon forests) or woodlands'),
('features', 'Subtropical and temperate rainforests or woodlands', 'Subtropical and temperate rainforests or woodlands'),
('features', 'Temperate needle-leaf forests or woodlands', 'Temperate needle-leaf forests or woodlands'),
('features', 'Tropical humid forests', 'Tropical humid forests'),
('features', 'Mixed island systems', 'Mixed island systems'),
('features', 'Tundra communities and barren Arctic deserts', 'Tundra communities and barren Arctic deserts'),
('features', 'Mixed mountain and highland systems with complex zonation', 'Mixed mountain and highland systems with complex zonation'),
('features', 'Cold-winter (continental) deserts and semideserts', 'Cold-winter (continental) deserts and semideserts'),
('features', 'Warm deserts and semideserts', 'Warm deserts and semideserts'),
('features', 'Bailey biome', 'Bailey biome'),
('features', 'Polar Domain (100)', 'Polar Domain (100)'),
('features', 'Humid Temperate Domain (200)', 'Humid Temperate Domain (200)'),
('features', 'Dry Domain (300)', 'Dry Domain (300)'),
('features', 'Humid Tropical Domain (400)', 'Humid Tropical Domain (400)'),
('features', 'Tundra Divsion (120)', 'Tundra Divsion (120)'),
('features', 'Subarctic Division - Mountain Provinces (M130)', 'Subarctic Division - Mountain Provinces (M130)'),
('features', 'Subarctic Division (130)', 'Subarctic Division (130)'),
('features', 'Tundra Division - Mountain Provinces (M120)', 'Tundra Division - Mountain Provinces (M120)'),
('features', 'Hot Continental Division (220)', 'Hot Continental Division (220)'),
('features', 'Subtropical Division (230)', 'Subtropical Division (230)'),
('features', 'Warm Continental Division (210)', 'Warm Continental Division (210)'),
('features', 'Warm Continental Division - Mountain Provinces (M210)', 'Warm Continental Division - Mountain Provinces (M210)'),
('features', 'Subtropical Division - Mountain Provinces (M230)', 'Subtropical Division - Mountain Provinces (M230)'),
('features', 'Hot Continental Division - Mountain Provinces (M220)', 'Hot Continental Division - Mountain Provinces (M220)'),
('features', 'Marine Division (240)', 'Marine Division (240)'),
('features', 'Marine Division - Mountain Provinces (M240)', 'Marine Division - Mountain Provinces (M240)'),
('features', 'Prairie Division (250)', 'Prairie Division (250)'),
('features', 'Mediterranean Division (260)', 'Mediterranean Division (260)'),
('features', 'Mediterranean Division - Mountain Provinces (M260)', 'Mediterranean Division - Mountain Provinces (M260)'),
('features', 'Tropical/Subtropical Desert Division (320)', 'Tropical/Subtropical Desert Division (320)'),
('features', 'Rainforest Division (420)', 'Rainforest Division (420)'),
('features', 'Temperate Desert Division (340)', 'Temperate Desert Division (340)'),
('features', 'Temperate Desert Division - Mountain Provinces (M340)', 'Temperate Desert Division - Mountain Provinces (M340)'),
('features', 'Temperate Steppe Division (330)', 'Temperate Steppe Division (330)'),
('features', 'Temperate Steppe Division - Mountain Provinces (M330)', 'Temperate Steppe Division - Mountain Provinces (M330)'),
('features', 'Tropical/Subtropical Steppe Division - Mountain Provinces (M310)', 'Tropical/Subtropical Steppe Division - Mountain Provinces (M310)'),
('features', 'Tropical/Subtropical Steppe Division (310)', 'Tropical/Subtropical Steppe Division (310)'),
('features', 'Rainforest Division - Mountain Provinces (M420)', 'Rainforest Division - Mountain Provinces (M420)'),
('features', 'Savanna Division (410)', 'Savanna Division (410)'),
('features', 'Savanna Division - Mountain Provinces (M410)', 'Savanna Division - Mountain Provinces (M410)'),
('features', 'silage', 'Silage'),
('features', 'animal manure', 'Animal manure'),
('features', 'fresh animal manure', 'Fresh animal manure'),
('features', 'mushroom compost', 'Mushroom compost'),
('features', 'wort', 'Wort'),
('features', 'beer wort', 'Beer wort'),
('features', 'acifified beer wort', 'Acifified beer wort'),
('features', 'animal house', 'Animal house'),
('features', 'cow shed', 'Cow shed'),
('features', 'piggery', 'Piggery'),
('features', 'sewage plant', 'Sewage plant'),
('features', 'brine', 'Brine'),
('features', 'bacon curing brine', 'Bacon curing brine'),
('features', 'Bleu  de Bresse', 'Bleu  de Bresse'),
('features', 'butter', 'Butter'),
('features', 'pickled cabbage', 'Pickled cabbage'),
('features', 'Camembert', 'Camembert'),
('features', 'cane sugar', 'Cane sugar'),
('features', 'Cheddar cheese', 'Cheddar cheese'),
('features', 'Brie', 'Brie'),
('features', 'Gouda', 'Gouda'),
('features', 'halloumi', 'Halloumi'),
('features', 'Gorgonzola', 'Gorgonzola'),
('features', 'Swiss cheese', 'Swiss cheese'),
('features', 'Emmenthal', 'Emmenthal'),
('features', 'Harzer', 'Harzer'),
('features', 'New Zealand Cheddar', 'New Zealand Cheddar'),
('features', 'Pont l''Eveque', 'Pont l''Eveque'),
('features', 'Vacherin Mont d''Or', 'Vacherin Mont d''Or'),
('features', 'pork', 'Pork'),
('features', 'cured meat', 'Cured meat'),
('features', 'drinking water', 'Drinking water'),
('features', 'distilled water', 'Distilled water'),
('features', 'chicken meat product', 'Chicken meat product'),
('features', 'beef', 'Beef'),
('features', 'bovine milk', 'Bovine milk'),
('features', 'ovine milk', 'Ovine milk'),
('features', 'caprine milk', 'Caprine milk'),
('features', 'grass silage', 'Grass silage'),
('features', 'ice cream', 'Ice cream'),
('features', 'seafood product', 'Seafood product'),
('features', 'manufactured product', 'Manufactured product'),
('features', 'anthropogenic abiotic mesoscopic feature', 'Anthropogenic abiotic mesoscopic feature'),
('features', 'glue', 'Glue'),
('features', 'jeotgal', 'Jeotgal'),
('features', 'Meshanger cheese', 'Meshanger cheese'),
('features', 'pork chop', 'Pork chop'),
('features', 'salad', 'Salad'),
('features', 'metal contaminated soil', 'Metal contaminated soil'),
('features', 'enriched soil', 'Enriched soil'),
('features', 'sarcosine enriched soil', 'Sarcosine enriched soil'),
('features', 'trimethylamine enriched soil', 'Trimethylamine enriched soil'),
('features', 'skatole enriched soil', 'Skatole enriched soil'),
('features', 'ethanol enriched soil', 'Ethanol enriched soil'),
('features', 'acetamide enriched soil', 'Acetamide enriched soil'),
('features', 'pantothenate enriched soil', 'Pantothenate enriched soil'),
('features', 'testosterone enriched soil', 'Testosterone enriched soil'),
('features', 'kynurenate enriched soil', 'Kynurenate enriched soil'),
('features', 'threonine enriched soil', 'Threonine enriched soil'),
('features', 'salicylate enriched soil', 'Salicylate enriched soil'),
('features', 'poly-beta-hydroxybutyrate enriched soil', 'Poly-beta-hydroxybutyrate enriched soil'),
('features', 'L-(+)-tartrate enriched soil', 'L-(+)-tartrate enriched soil'),
('features', 'quinate enriched soil', 'Quinate enriched soil'),
('features', 'tap water', 'Tap water'),
('features', 'bore hole water', 'Bore hole water'),
('features', 'tannery', 'Tannery'),
('features', 'tempeh', 'Tempeh'),
('features', 'horse manure', 'Horse manure'),
('features', 'pig manure', 'Pig manure'),
('features', 'industrial building', 'Industrial building'),
('features', 'dairy', 'Dairy'),
('features', 'food processing factory', 'Food processing factory'),
('features', 'bakery', 'Bakery'),
('features', 'straw', 'Straw'),
('features', 'rice straw', 'Rice straw'),
('features', 'fermented rice beverage', 'Fermented rice beverage'),
('features', 'amasake', 'Amasake'),
('features', 'fermented dairy product', 'Fermented dairy product'),
('features', 'fermented fish product', 'Fermented fish product'),
('features', 'sea water fish product', 'Sea water fish product'),
('features', 'flour', 'Flour'),
('features', 'plant fruit food product', 'Plant fruit food product'),
('features', 'fruit extract product', 'Fruit extract product'),
('features', 'apple juice', 'Apple juice'),
('features', 'awamori', 'Awamori'),
('features', 'bacon', 'Bacon'),
('features', 'fermented millet food product', 'Fermented millet food product'),
('features', 'millet beer', 'Millet beer'),
('features', 'farmyard manure', 'Farmyard manure'),
('features', 'brewery', 'Brewery'),
('features', 'bottled beer', 'Bottled beer'),
('features', 'blue cheese', 'Blue cheese'),
('features', 'bottled fruit product', 'Bottled fruit product'),
('features', 'buttermilk', 'Buttermilk'),
('features', 'canned fruit product', 'Canned fruit product'),
('features', 'fermented fruit product', 'Fermented fruit product'),
('features', 'cosmetic product', 'Cosmetic product'),
('features', 'face cream product', 'Face cream product'),
('features', 'paper product', 'Paper product'),
('features', 'currency note', 'Currency note'),
('features', 'miso', 'Miso'),
('features', 'must', 'Must'),
('features', 'rye grass silage', 'Rye grass silage'),
('features', 'aviation fuel', 'Aviation fuel'),
('features', 'yeast cake', 'Yeast cake'),
('features', 'vinegar', 'Vinegar'),
('features', 'malt vinegar', 'Malt vinegar'),
('features', 'nonfat dry milk', 'Nonfat dry milk'),
('features', 'poultry deep litter', 'Poultry deep litter'),
('features', 'sake brewery', 'Sake brewery'),
('features', 'sake', 'Sake'),
('features', 'salt pork', 'Salt pork'),
('features', 'chalk soil', 'Chalk soil'),
('features', 'fermented soybean product', 'Fermented soybean product'),
('features', 'research station', 'Research station'),
('features', 'stable manure', 'Stable manure'),
('features', 'pickled food product', 'Pickled food product'),
('features', 'tape kefan', 'Tape kefan'),
('features', 'scum', 'Scum'),
('features', 'warehouse', 'Warehouse'),
('features', 'tobacco warehouse', 'Tobacco warehouse'),
('features', 'anaerobic digester sludge', 'Anaerobic digester sludge'),
('features', 'Bondon cheese', 'Bondon cheese'),
('features', 'creamery', 'Creamery'),
('features', 'air filter', 'Air filter'),
('features', 'bitter cheese', 'Bitter cheese'),
('features', 'sugar', 'Sugar'),
('features', 'brown sugar', 'Brown sugar'),
('features', 'evaporated milk product', 'Evaporated milk product'),
('features', 'kefir', 'Kefir'),
('features', 'linseed oil', 'Linseed oil'),
('features', 'maize flour', 'Maize flour'),
('features', 'potato silage', 'Potato silage'),
('features', 'sour milk', 'Sour milk'),
('features', 'dried milk product', 'Dried milk product'),
('features', 'travertine', 'Travertine'),
('features', 'sawmill', 'Sawmill'),
('features', 'karst field', 'Karst field'),
('features', 'foam', 'Foam'),
('features', 'sea foam', 'Sea foam'),
('features', 'paddy field soil', 'Paddy field soil'),
('features', 'alpine soil', 'Alpine soil'),
('features', 'arable soil', 'Arable soil'),
('features', 'roadside soil', 'Roadside soil'),
('features', 'allotment garden soil', 'Allotment garden soil'),
('features', 'allotment garden', 'Allotment garden'),
('features', 'savanna soil', 'Savanna soil'),
('features', 'compost soil', 'Compost soil'),
('features', 'dry soil', 'Dry soil'),
('features', 'farm soil', 'Farm soil'),
('features', 'grassland soil', 'Grassland soil'),
('features', 'jungle soil', 'Jungle soil'),
('features', 'sawah soil', 'Sawah soil'),
('features', 'urea enriched soil', 'Urea enriched soil'),
('features', 'fertilized soil', 'Fertilized soil'),
('features', 'field soil', 'Field soil'),
('features', 'lawn soil', 'Lawn soil'),
('features', 'bacteria enriched soil', 'Bacteria enriched soil'),
('features', 'alluvial swamp soil', 'Alluvial swamp soil'),
('features', 'alluvial paddy field soil', 'Alluvial paddy field soil'),
('features', 'burned soil', 'Burned soil'),
('features', 'meadow soil', 'Meadow soil'),
('features', 'chloropicrine-enriched soil', 'Chloropicrine-enriched soil'),
('features', 'humus-rich acidic ash soil', 'Humus-rich acidic ash soil'),
('features', 'pond soil', 'Pond soil'),
('features', 'frozen compost soil', 'Frozen compost soil'),
('features', 'limed soil', 'Limed soil'),
('features', 'manured soil', 'Manured soil'),
('features', 'orchid soil', 'Orchid soil'),
('features', 'mountain forest soil', 'Mountain forest soil'),
('features', 'beech forest soil', 'Beech forest soil'),
('features', 'muddy soil', 'Muddy soil'),
('features', 'orchard soil', 'Orchard soil'),
('features', 'pasture soil', 'Pasture soil'),
('features', 'peat soil', 'Peat soil'),
('features', 'salt contaminated soil', 'Salt contaminated soil'),
('features', 'peaty paddy field soil', 'Peaty paddy field soil'),
('features', 'steppe soil', 'Steppe soil'),
('features', 'tropical soil', 'Tropical soil'),
('features', 'vegetable garden soil', 'Vegetable garden soil'),
('features', 'greenhouse soil', 'Greenhouse soil'),
('features', 'heat stressed soil', 'Heat stressed soil'),
('features', 'ornithogenic soil', 'Ornithogenic soil'),
('features', 'leafy wood soil', 'Leafy wood soil'),
('features', 'spruce forest soil', 'Spruce forest soil'),
('features', 'volcanic soil', 'Volcanic soil'),
('features', 'upland soil', 'Upland soil'),
('features', 'eucalyptus forest soil', 'Eucalyptus forest soil'),
('features', 'rubber plantation soil', 'Rubber plantation soil'),
('features', 'blue-grass field soil', 'Blue-grass field soil'),
('features', 'red soil', 'Red soil'),
('features', 'sterile water', 'Sterile water'),
('features', 'underground water', 'Underground water'),
('features', 'muddy water', 'Muddy water'),
('features', 'water scum', 'Water scum'),
('features', 'marine mud', 'Marine mud'),
('features', 'marine sludge', 'Marine sludge'),
('features', 'lake bottom mud', 'Lake bottom mud'),
('features', 'acid dune sand', 'Acid dune sand'),
('features', 'rocky sand', 'Rocky sand'),
('features', 'desert sand', 'Desert sand'),
('features', 'rhizosphere', 'Rhizosphere'),
('features', 'bulk soil', 'Bulk soil'),
('features', 'animal habitation', 'Animal habitation'),
('features', 'nest of ant', 'Nest of ant'),
('features', 'nest of bird', 'Nest of bird'),
('features', 'Tropical and subtropical coniferous forest biome', 'Tropical and subtropical coniferous forest biome'),
('features', 'animal-associated habitat', 'Animal-associated habitat'),
('features', 'plant-associated habitat', 'Plant-associated habitat'),
('features', 'mammalia-associated habitat', 'Mammalia-associated habitat'),
('features', 'human-associated habitat', 'Human-associated habitat'),
('features', 'insecta-associated habitat', 'Insecta-associated habitat'),
('features', 'ice rise', 'Ice rise'),
('features', 'ice piedmont', 'Ice piedmont'),
('features', 'strand crack', 'Strand crack'),
('features', 'fomite', 'Fomite'),
('features', 'midden', 'Midden'),
('features', 'environmental material', 'Environmental material'),
('features', 'surface', 'Surface'),
('features', 'aerosol', 'Aerosol'),
('features', 'emulsion', 'Emulsion'),
('features', 'medical instrument', 'Medical instrument'),
('features', 'vivarium', 'Vivarium'),
('features', 'dolomite', 'Dolomite'),
('features', 'botanical garden', 'Botanical garden'),
('features', 'zoological garden', 'Zoological garden'),
('features', 'ocean time series station', 'Ocean time series station'),
('features', 'aquifer', 'Aquifer'),
('features', 'karst cave', 'Karst cave'),
('features', 'animal food product', 'Animal food product'),
('features', 'anthropogenic environmental material', 'Anthropogenic environmental material'),
('features', 'cereal food product', 'Cereal food product'),
('features', 'agricultural environmental material', 'Agricultural environmental material'),
('features', 'beverage product', 'Beverage product'),
('features', 'fermented beverage', 'Fermented beverage'),
('features', 'fermented grape beverage', 'Fermented grape beverage'),
('features', 'fermented Elaeis Palm beverage', 'Fermented Elaeis Palm beverage'),
('features', 'fermented sugar cane beverage', 'Fermented sugar cane beverage'),
('features', 'fermented apple beverage', 'Fermented apple beverage'),
('features', 'apple beverage', 'Apple beverage'),
('features', 'orange fruit beverage', 'Orange fruit beverage'),
('features', 'grape beverage', 'Grape beverage'),
('features', 'fermented cereal beverage', 'Fermented cereal beverage'),
('features', 'fermented agave beverage', 'Fermented agave beverage'),
('features', 'fermented soya product', 'Fermented soya product'),
('features', 'sea water fish egg product', 'Sea water fish egg product'),
('features', 'avian egg product', 'Avian egg product'),
('features', 'camelid dairy product', 'Camelid dairy product'),
('features', 'bovine dairy product', 'Bovine dairy product'),
('features', 'buffalo dairy product', 'Buffalo dairy product'),
('features', 'caprine dairy product', 'Caprine dairy product'),
('features', 'donkey dairy product', 'Donkey dairy product'),
('features', 'equine dairy product', 'Equine dairy product'),
('features', 'ovine dairy product', 'Ovine dairy product'),
('features', 'yak dairy product', 'Yak dairy product'),
('features', 'zebra dairy product', 'Zebra dairy product'),
('features', 'reindeer dairy product', 'Reindeer dairy product'),
('features', 'water buffalo dairy product', 'Water buffalo dairy product'),
('features', 'horse dairy product', 'Horse dairy product'),
('features', 'domestic cattle dairy product', 'Domestic cattle dairy product'),
('features', 'cervid dairy product', 'Cervid dairy product'),
('features', 'camelid milk', 'Camelid milk'),
('features', 'equine milk', 'Equine milk'),
('features', 'cervid milk', 'Cervid milk'),
('features', 'cow''s milk', 'Cow''s milk'),
('features', 'caprine cheese product', 'Caprine cheese product'),
('features', 'ovine cheese product', 'Ovine cheese product'),
('features', 'bovine cheese product', 'Bovine cheese product'),
('features', 'cow''s milk cheese', 'Cow''s milk cheese'),
('features', 'Limburger', 'Limburger'),
('features', 'goat''s milk cheese', 'Goat''s milk cheese'),
('features', 'sheep''s milk cheese', 'Sheep''s milk cheese'),
('features', 'poultry meat product', 'Poultry meat product'),
('features', 'porcine meat product', 'Porcine meat product'),
('features', 'condiment', 'Condiment'),
('features', 'bovine meat product', 'Bovine meat product'),
('features', 'distilled fermented grain beverage', 'Distilled fermented grain beverage'),
('features', 'distilled fermented beverage', 'Distilled fermented beverage'),
('features', 'soya food product', 'Soya food product'),
('features', 'tea-based beverage', 'Tea-based beverage'),
('features', 'coffee-based beverage', 'Coffee-based beverage'),
('features', 'fruit juice beverage', 'Fruit juice beverage'),
('features', 'wheat product', 'Wheat product'),
('features', 'maize product', 'Maize product'),
('features', 'fungal product', 'Fungal product'),
('features', 'yeast product', 'Yeast product'),
('features', 'microbial food product', 'Microbial food product'),
('features', 'solanaceous root product', 'Solanaceous root product'),
('features', 'plant root food product', 'Plant root food product'),
('features', 'potato product', 'Potato product'),
('features', 'confectionery product', 'Confectionery product'),
('features', 'cucurbit fruit product', 'Cucurbit fruit product'),
('features', 'citrus fruit product', 'Citrus fruit product'),
('features', 'melon fruit product', 'Melon fruit product'),
('features', 'Cucumis melo fruit', 'Cucumis melo fruit'),
('features', 'Citrullus lanatus fruit', 'Citrullus lanatus fruit'),
('features', 'watermelon', 'Watermelon'),
('features', 'citrus fruit beverage', 'Citrus fruit beverage'),
('features', 'pomaceous fruit beverage', 'Pomaceous fruit beverage'),
('features', 'pomaceous fruit product', 'Pomaceous fruit product'),
('features', 'fermented pomaceous fruit beverage', 'Fermented pomaceous fruit beverage'),
('features', 'pomaceous fruit extract', 'Pomaceous fruit extract'),
('features', 'citrus fruit extract', 'Citrus fruit extract'),
('features', 'grape extract', 'Grape extract'),
('features', 'solanaceous fruit product', 'Solanaceous fruit product'),
('features', 'tomato product', 'Tomato product'),
('features', 'solanaceous food product', 'Solanaceous food product'),
('features', 'plant inflorescence food product', 'Plant inflorescence food product'),
('features', 'amaranthaceous food product', 'Amaranthaceous food product'),
('features', 'leguminous food product', 'Leguminous food product'),
('features', 'cruciferous food product', 'Cruciferous food product'),
('features', 'grape fruit product', 'Grape fruit product'),
('features', 'cruciferous inflorescence food product', 'Cruciferous inflorescence food product'),
('features', 'nut food product', 'Nut food product'),
('features', 'plant seed food product', 'Plant seed food product'),
('features', 'plant lipid food product', 'Plant lipid food product'),
('features', 'plant stem food product', 'Plant stem food product'),
('features', 'invertebrate food product', 'Invertebrate food product'),
('features', 'insect food product', 'Insect food product'),
('features', 'honey product', 'Honey product'),
('features', 'amaranthaceous inflorescence food product', 'Amaranthaceous inflorescence food product'),
('features', 'processed food product', 'Processed food product'),
('features', 'cooked food product', 'Cooked food product'),
('features', 'pickled cruciferous food product', 'Pickled cruciferous food product'),
('features', 'bread', 'Bread'),
('features', 'algal food product', 'Algal food product'),
('features', 'rice product', 'Rice product'),
('features', 'buckewheat product', 'Buckewheat product'),
('features', 'sorghum product', 'Sorghum product'),
('features', 'milet product', 'Milet product'),
('features', 'oats product', 'Oats product'),
('features', 'rye product', 'Rye product'),
('features', 'barley product', 'Barley product'),
('features', 'quinoa product', 'Quinoa product'),
('features', 'fonio product', 'Fonio product'),
('features', 'dry peas product', 'Dry peas product'),
('features', 'lentil product', 'Lentil product'),
('features', 'pigeon pea product', 'Pigeon pea product'),
('features', 'bambara groundnut product', 'Bambara groundnut product'),
('features', 'dry broad beans product', 'Dry broad beans product'),
('features', 'chickpea product', 'Chickpea product'),
('features', 'cowpea product', 'Cowpea product'),
('features', 'dry beans product', 'Dry beans product'),
('features', 'winged bean product', 'Winged bean product'),
('features', 'vetch seed product', 'Vetch seed product'),
('features', 'yam bean product', 'Yam bean product'),
('features', 'velvet bean product', 'Velvet bean product'),
('features', 'lupin seed product', 'Lupin seed product'),
('features', 'jack bean product', 'Jack bean product'),
('features', 'hyacinth bean product', 'Hyacinth bean product'),
('features', 'pulses', 'Pulses'),
('features', 'wheat flour', 'Wheat flour'),
('features', 'pasta', 'Pasta'),
('features', 'pastry', 'Pastry'),
('features', 'baked food product', 'Baked food product'),
('features', 'candy', 'Candy'),
('features', 'cacao food product', 'Cacao food product'),
('features', 'cream', 'Cream'),
('features', 'milk', 'Milk'),
('features', 'bee food product', 'Bee food product'),
('features', 'cooked smoked sausage', 'Cooked smoked sausage'),
('features', 'smoked sausage', 'Smoked sausage'),
('features', 'fresh smoked sausage', 'Fresh smoked sausage'),
('features', 'fresh sausage', 'Fresh sausage'),
('features', 'dry sausage', 'Dry sausage'),
('features', 'cooked sausage', 'Cooked sausage'),
('features', 'smoked meat', 'Smoked meat'),
('features', 'fruit preserve', 'Fruit preserve'),
('features', 'jam', 'Jam'),
('features', 'rennet product', 'Rennet product'),
('features', 'processed cheese product', 'Processed cheese product'),
('features', 'mustard', 'Mustard'),
('features', 'creamy salad dressing', 'Creamy salad dressing'),
('features', 'vinaigrette', 'Vinaigrette'),
('features', 'vegetable oil', 'Vegetable oil'),
('features', 'nut oil', 'Nut oil'),
('features', 'mayonnaise', 'Mayonnaise'),
('features', 'soy sauce', 'Soy sauce'),
('features', 'fresh  sea water fish', 'Fresh  sea water fish'),
('features', 'natural rennet', 'Natural rennet'),
('features', 'microbial rennet', 'Microbial rennet'),
('features', 'vegetable rennet', 'Vegetable rennet'),
('features', 'genetically engineered rennet', 'Genetically engineered rennet'),
('features', 'processed pork', 'Processed pork'),
('features', 'spice product', 'Spice product'),
('features', 'animal lipid food product', 'Animal lipid food product'),
('features', 'coffee', 'Coffee'),
('features', 'tea', 'Tea'),
('features', 'hot chocolate', 'Hot chocolate'),
('features', 'mate', 'Mate'),
('features', 'naturally occuring environmental material', 'Naturally occuring environmental material'),
('features', 'dry stream valley', 'Dry stream valley'),
('features', 'dry river valley', 'Dry river valley'),
('features', 'fish food product', 'Fish food product'),
('features', 'freshwater fish product', 'Freshwater fish product'),
('features', 'fish egg product', 'Fish egg product'),
('features', 'avian food product', 'Avian food product'),
('features', 'animal derived beverage', 'Animal derived beverage'),
('features', 'plant derived beverage', 'Plant derived beverage'),
('features', 'fermented plant derived beverage', 'Fermented plant derived beverage'),
('features', 'non-fermented plant derived beverage', 'Non-fermented plant derived beverage'),
('features', 'humus', 'Humus'),
('features', 'mud', 'Mud'),
('features', 'water well', 'Water well'),
('features', 'oil well', 'Oil well'),
('features', 'concentration basin mediterranean sea biome', 'Concentration basin mediterranean sea biome'),
('features', 'upwelling', 'Upwelling'),
('features', 'coastal upwelling', 'Coastal upwelling'),
('features', 'microbial feature', 'Microbial feature'),
('features', 'microbial mat', 'Microbial mat'),
('features', 'biotic mesoscopic physical object', 'Biotic mesoscopic physical object'),
('features', 'abiotic mesoscopic physical object', 'Abiotic mesoscopic physical object'),
('features', 'dairy product', 'Dairy product'),
('features', 'milk product', 'Milk product'),
('features', 'fermented food product', 'Fermented food product'),
('features', 'wine', 'Wine'),
('features', 'beer', 'Beer'),
('features', 'silt', 'Silt'),
('features', 'sand', 'Sand'),
('features', 'gravel', 'Gravel'),
('features', 'cave floor', 'Cave floor'),
('features', 'estuarine biome', 'Estuarine biome'),
('features', 'mangrove biome', 'Mangrove biome'),
('features', 'marine salt marsh biome', 'Marine salt marsh biome'),
('features', 'marine pelagic biome', 'Marine pelagic biome'),
('features', 'marine benthic biome', 'Marine benthic biome'),
('features', 'marine neritic benthic zone biome', 'Marine neritic benthic zone biome'),
('features', 'marine bathyal zone biome', 'Marine bathyal zone biome'),
('features', 'marine abyssal zone biome', 'Marine abyssal zone biome'),
('features', 'marine hadal zone biome', 'Marine hadal zone biome'),
('features', 'marine reef biome', 'Marine reef biome'),
('features', 'marine hydrothermal vent biome', 'Marine hydrothermal vent biome'),
('features', 'marine feature', 'Marine feature'),
('features', 'neritic pelagic zone biome', 'Neritic pelagic zone biome'),
('features', 'oceanic pelagic zone biome', 'Oceanic pelagic zone biome'),
('features', 'oceanic sea surface microlayer biome', 'Oceanic sea surface microlayer biome'),
('features', 'oceanic epipelagic zone biome', 'Oceanic epipelagic zone biome'),
('features', 'oceanic mesopelagic zone biome', 'Oceanic mesopelagic zone biome'),
('features', 'oceanic bathypelagic zone biome', 'Oceanic bathypelagic zone biome'),
('features', 'oceanic abyssopelagic zone biome', 'Oceanic abyssopelagic zone biome'),
('features', 'oceanic hadal pelagic zone biome', 'Oceanic hadal pelagic zone biome'),
('features', 'oceanic benthopelagic zone biome', 'Oceanic benthopelagic zone biome'),
('features', 'neritic sea surface microlayer biome', 'Neritic sea surface microlayer biome'),
('features', 'neritic epipelagic zone biome', 'Neritic epipelagic zone biome'),
('features', 'neritic mesopelagic zone biome', 'Neritic mesopelagic zone biome'),
('features', 'marine pelagic feature', 'Marine pelagic feature'),
('features', 'epeiric sea biome', 'Epeiric sea biome'),
('features', 'marginal sea biome', 'Marginal sea biome'),
('features', 'mediterranean sea biome', 'Mediterranean sea biome'),
('features', 'ocean biome', 'Ocean biome'),
('features', 'marine coral reef biome', 'Marine coral reef biome'),
('features', 'marine subtidal rocky reef biome', 'Marine subtidal rocky reef biome'),
('features', 'marine black smoker biome', 'Marine black smoker biome'),
('features', 'marine white smoker biome', 'Marine white smoker biome'),
('features', 'marine ultramafic hydrothermal vent biome', 'Marine ultramafic hydrothermal vent biome'),
('features', 'marine basaltic hydrothermal vent biome', 'Marine basaltic hydrothermal vent biome'),
('features', 'marine bulk water', 'Marine bulk water'),
('features', 'estuarine bulk water', 'Estuarine bulk water'),
('features', 'marine algal bloom', 'Marine algal bloom'),
('features', 'kelp forest', 'Kelp forest'),
('features', 'sea grass bed', 'Sea grass bed'),
('features', 'marine brine pool', 'Marine brine pool'),
('features', 'marine wind mixed layer', 'Marine wind mixed layer'),
('features', 'marine benthic storm', 'Marine benthic storm'),
('features', 'marine upwelling', 'Marine upwelling'),
('features', 'marine downwelling', 'Marine downwelling'),
('features', 'marine oxygen minimum zone', 'Marine oxygen minimum zone'),
('features', 'marine anoxic zone', 'Marine anoxic zone'),
('features', 'marine current', 'Marine current'),
('features', 'marine streamer', 'Marine streamer'),
('features', 'mesoscale marine eddy', 'Mesoscale marine eddy'),
('features', 'terrigenous sediment', 'Terrigenous sediment'),
('features', 'oceanic front', 'Oceanic front'),
('features', 'marine Taylor column', 'Marine Taylor column'),
('features', 'marine oligotrophic desert', 'Marine oligotrophic desert'),
('features', 'oceanic gyre', 'Oceanic gyre'),
('features', 'marine thermocline', 'Marine thermocline'),
('features', 'marine chemocline', 'Marine chemocline'),
('features', 'marine pycnocline', 'Marine pycnocline'),
('features', 'marine nutricline', 'Marine nutricline'),
('features', 'marine lysocline', 'Marine lysocline'),
('features', 'pelagic isothermal surface', 'Pelagic isothermal surface'),
('features', 'pelagic isohaline surface', 'Pelagic isohaline surface'),
('features', 'biogenous sediment', 'Biogenous sediment'),
('features', 'pelagic isopycnal surface', 'Pelagic isopycnal surface'),
('features', 'estuarine front', 'Estuarine front'),
('features', 'plume front', 'Plume front'),
('features', 'coastal buoyancy current front', 'Coastal buoyancy current front'),
('features', 'tidal mixing front', 'Tidal mixing front'),
('features', 'mid-shelf fronts', 'Mid-shelf fronts'),
('features', 'shelf-slope/shelf-break front', 'Shelf-slope/shelf-break front'),
('features', 'coastal upwelling front', 'Coastal upwelling front'),
('features', 'topographic upwelling front', 'Topographic upwelling front'),
('features', 'equatorial upwelling front', 'Equatorial upwelling front'),
('features', 'boundary current front', 'Boundary current front'),
('features', 'subtropical convergence front', 'Subtropical convergence front'),
('features', 'marginal ice zone front', 'Marginal ice zone front'),
('features', 'water mass front', 'Water mass front'),
('features', 'surface convergence', 'Surface convergence'),
('features', 'deep ocean current', 'Deep ocean current'),
('features', 'marine surface current', 'Marine surface current'),
('features', 'along-front current', 'Along-front current'),
('features', 'warm surface current', 'Warm surface current'),
('features', 'cold surface current', 'Cold surface current'),
('features', 'western boundary current', 'Western boundary current'),
('features', 'eastern boundary current', 'Eastern boundary current'),
('features', 'marine benthic feature', 'Marine benthic feature'),
('features', 'permanent marine thermocline', 'Permanent marine thermocline'),
('features', 'seasonal marine thermocline', 'Seasonal marine thermocline'),
('features', 'marine cold-water sphere', 'Marine cold-water sphere'),
('features', 'marine warm-water sphere', 'Marine warm-water sphere'),
('features', 'hydrogenous sediment', 'Hydrogenous sediment'),
('features', 'cosmogenous sediment', 'Cosmogenous sediment'),
('features', 'polymetallic nodule', 'Polymetallic nodule'),
('features', 'suspended sediment', 'Suspended sediment'),
('features', 'boulder sediment', 'Boulder sediment'),
('features', 'cobble sediment', 'Cobble sediment'),
('features', 'pebble sediment', 'Pebble sediment'),
('features', 'granular sediment', 'Granular sediment'),
('features', 'sandy sediment', 'Sandy sediment'),
('features', 'silty sediment', 'Silty sediment'),
('features', 'clay sediment', 'Clay sediment'),
('features', 'colloidal sediment', 'Colloidal sediment'),
('features', 'marine hydrothermal vent', 'Marine hydrothermal vent'),
('features', 'marine sponge reef biome', 'Marine sponge reef biome'),
('features', 'neritic supra-littoral zone', 'Neritic supra-littoral zone'),
('features', 'nertic littoral zone', 'Nertic littoral zone'),
('features', 'neritic sub-littoral zone', 'Neritic sub-littoral zone'),
('features', 'marine cold seep biome', 'Marine cold seep biome'),
('features', 'dilution basin mediterranean sea biome', 'Dilution basin mediterranean sea biome'),
('features', 'marine hydrothermal vent chimney', 'Marine hydrothermal vent chimney'),
('features', 'marine hydrothermal plume', 'Marine hydrothermal plume'),
('features', 'mesophilic sediment', 'Mesophilic sediment'),
('features', 'thermophilic sediment', 'Thermophilic sediment'),
('features', 'hyperthermophilic sediment', 'Hyperthermophilic sediment'),
('features', 'hydrothermal fluid', 'Hydrothermal fluid'),
('features', 'nitrate-reducing sediment', 'Nitrate-reducing sediment'),
('features', 'drop stone', 'Drop stone'),
('features', 'organic matter fall', 'Organic matter fall'),
('features', 'plant matter fall', 'Plant matter fall'),
('features', 'animal matter fall', 'Animal matter fall'),
('features', 'whale fall', 'Whale fall'),
('features', 'seal fall', 'Seal fall'),
('features', 'wood fall', 'Wood fall'),
('features', 'marine reef', 'Marine reef'),
('features', 'marine coral reef flat zone', 'Marine coral reef flat zone'),
('features', 'marine coral reef back reef', 'Marine coral reef back reef'),
('features', 'marine coral reef crest', 'Marine coral reef crest'),
('features', 'marine coral reef fore reef', 'Marine coral reef fore reef'),
('features', 'marine coral reef buttress zone', 'Marine coral reef buttress zone'),
('features', 'marine coral reef deep fore reef', 'Marine coral reef deep fore reef'),
('features', 'marine subtidal rocky reef', 'Marine subtidal rocky reef'),
('features', 'manganese-reducing sediment', 'Manganese-reducing sediment'),
('features', 'iron-reducing sediment', 'Iron-reducing sediment'),
('features', 'sulphate-reducing sediment', 'Sulphate-reducing sediment'),
('features', 'carbon dioxide-reducing sediment', 'Carbon dioxide-reducing sediment'),
('features', 'organic material', 'Organic material'),
('features', 'biofilm material', 'Biofilm material'),
('features', 'microbial mat material', 'Microbial mat material'),
('features', 'marine snow', 'Marine snow'),
('features', 'organic feature', 'Organic feature'),
('features', 'marine pockmark', 'Marine pockmark'),
('features', 'marine sponge reef', 'Marine sponge reef'),
('features', 'organ', 'Organ'),
('features', 'photophore', 'Photophore'),
('features', 'root nodule', 'Root nodule'),
('features', 'trophosome', 'Trophosome'),
('features', 'mycetome', 'Mycetome'),
('features', 'determinate root nodule', 'Determinate root nodule'),
('features', 'indeterminate root nodule', 'Indeterminate root nodule'),
('features', 'indeterminate root nodule active meristem', 'Indeterminate root nodule active meristem'),
('features', 'indeterminate root nodule infection zone', 'Indeterminate root nodule infection zone'),
('features', 'indeterminate root nodule nitrogen fixation zone', 'Indeterminate root nodule nitrogen fixation zone'),
('features', 'indeterminate root nodule senescent zone', 'Indeterminate root nodule senescent zone'),
('features', 'anoxic water', 'Anoxic water'),
('features', 'hypodermic needle', 'Hypodermic needle'),
('features', 'textile', 'Textile'),
('features', 'bedclothing', 'Bedclothing'),
('features', 'pockmark field', 'Pockmark field'),
('features', 'nesting material', 'Nesting material'),
('features', 'livestock-associated habitat', 'Livestock-associated habitat'),
('features', 'cultured habitat', 'Cultured habitat'),
('features', 'tissue culture', 'Tissue culture'),
('features', 'cell culture', 'Cell culture'),
('features', 'plant tissue culture', 'Plant tissue culture'),
('features', 'organ culture', 'Organ culture'),
('features', 'buffalo milk', 'Buffalo milk'),
('features', 'camel milk', 'Camel milk'),
('features', 'donkey milk', 'Donkey milk'),
('features', 'horse milk', 'Horse milk'),
('features', 'reindeer milk', 'Reindeer milk'),
('features', 'water buffalo milk', 'Water buffalo milk'),
('features', 'yak milk', 'Yak milk'),
('features', 'zebra milk', 'Zebra milk'),
('features', 'bodily fluid', 'Bodily fluid'),
('features', 'blood', 'Blood'),
('features', 'amniotic fluid', 'Amniotic fluid'),
('features', 'excreta', 'Excreta'),
('features', 'bile', 'Bile'),
('features', 'aqueous humour', 'Aqueous humour'),
('features', 'sweat', 'Sweat'),
('features', 'chyme', 'Chyme'),
('features', 'blood plasma', 'Blood plasma'),
('features', 'ear wax', 'Ear wax'),
('features', 'cerebrospinal fluid', 'Cerebrospinal fluid'),
('features', 'chyle', 'Chyle'),
('features', 'breast milk', 'Breast milk'),
('features', 'vitreous humor', 'Vitreous humor'),
('features', 'pleural effusion', 'Pleural effusion'),
('features', 'tears', 'Tears'),
('features', 'oronasal secretion', 'Oronasal secretion'),
('features', 'saliva', 'Saliva'),
('features', 'sebum', 'Sebum'),
('features', 'pus', 'Pus'),
('features', 'synovial fluid', 'Synovial fluid'),
('features', 'mucus', 'Mucus'),
('features', 'lymph', 'Lymph'),
('features', 'interstitial fluid', 'Interstitial fluid'),
('features', 'biological product', 'Biological product'),
('features', 'siliceous ooze', 'Siliceous ooze'),
('features', 'red clay', 'Red clay'),
('features', 'calcareous ooze', 'Calcareous ooze'),
('features', 'animal feed', 'Animal feed'),
('features', 'contaminated animal feed', 'Contaminated animal feed'),
('features', 'coastal water body', 'Coastal water body'),
('features', 'spinach', 'Spinach'),
('features', 'unpasteurized milk product', 'Unpasteurized milk product'),
('features', 'umbrella', 'Umbrella'),
('features', 'hide', 'Hide'),
('features', 'bone meal', 'Bone meal'),
('features', 'plant feed', 'Plant feed'),
('features', 'egg product', 'Egg product'),
('features', 'hen''s egg product', 'Hen''s egg product'),
('features', 'cloth', 'Cloth'),
('features', 'surface soil', 'Surface soil'),
('features', 'apple cider', 'Apple cider'),
('features', 'unpasteurized orange juice', 'Unpasteurized orange juice'),
('features', 'dessert', 'Dessert'),
('features', 'cake', 'Cake'),
('features', 'cake icing', 'Cake icing'),
('features', 'chocolate', 'Chocolate'),
('features', 'custard', 'Custard'),
('features', 'ground beef', 'Ground beef'),
('features', 'poultry product', 'Poultry product'),
('features', 'duck meat product', 'Duck meat product'),
('features', 'goose meat product', 'Goose meat product'),
('features', 'turkey meat product', 'Turkey meat product'),
('features', 'mushroom', 'Mushroom'),
('features', 'bean plant', 'Bean plant'),
('features', 'cantaloupe', 'Cantaloupe'),
('features', 'peanut plant', 'Peanut plant'),
('features', 'potato salad', 'Potato salad'),
('features', 'salad dressing', 'Salad dressing'),
('features', 'clam product', 'Clam product'),
('features', 'oyster product', 'Oyster product'),
('features', 'shellfish product', 'Shellfish product'),
('features', 'letter', 'Letter'),
('features', 'unpasteurized goat milk cheese', 'Unpasteurized goat milk cheese'),
('features', 'Pecorino cheese', 'Pecorino cheese'),
('features', 'goat manure', 'Goat manure'),
('features', 'unpasteurized sheep milk cheese', 'Unpasteurized sheep milk cheese'),
('features', 'unpasteruized cow milk cheese', 'Unpasteruized cow milk cheese'),
('features', 'unpasteurized camel milk', 'Unpasteurized camel milk'),
('features', 'unpasteurized caprine milk', 'Unpasteurized caprine milk'),
('features', 'unpasteurized ovine milk', 'Unpasteurized ovine milk'),

 -- enable export
('categories', 'features','exported'),


--Biomes
('biomeList', 'aquatic biome', 'aquatic biome'),
('biomeList', 'freshwater biome', 'freshwater biome'),
('biomeList', 'Large lake biome', 'Large lake biome'),
('biomeList', 'Large river biome', 'Large river biome'),
('biomeList', 'Large river delta biome', 'Large river delta biome'),
('biomeList', 'Large river headwater biome', 'Large river headwater biome'),
('biomeList', 'Small lake biome', 'Small lake biome'),
('biomeList', 'Small river biome', 'Small river biome'),
('biomeList', 'Xeric basin biome', 'Xeric basin biome'),
('biomeList', 'marine biome', 'marine biome'),
('biomeList', 'epeiric sea biome', 'epeiric sea biome'),
('biomeList', 'estuarine biome', 'estuarine biome'),
('biomeList', 'mangrove biome', 'mangrove biome'),
('biomeList', 'marginal sea biome', 'marginal sea biome'),
('biomeList', 'marine benthic biome', 'marine benthic biome'),
('biomeList', 'marine abyssal zone biome', 'marine abyssal zone biome'),
('biomeList', 'marine bathyal zone biome', 'marine bathyal zone biome'),
('biomeList', 'marine cold seep biome', 'marine cold seep biome'),
('biomeList', 'marine hadal zone biome', 'marine hadal zone biome'),
('biomeList', 'marine hydrothermal vent biome', 'marine hydrothermal vent biome'),
('biomeList', 'marine basaltic hydrothermal vent biome', 'marine basaltic hydrothermal vent biome'),
('biomeList', 'marine black smoker biome', 'marine black smoker biome'),
('biomeList', 'marine ultramafic hydrothermal vent biome', 'marine ultramafic hydrothermal vent biome'),
('biomeList', 'marine white smoker biome', 'marine white smoker biome'),
('biomeList', 'marine neritic benthic zone biome', 'marine neritic benthic zone biome'),
('biomeList', 'neritic sub-littoral zone', 'neritic sub-littoral zone'),
('biomeList', 'neritic supra-littoral zone', 'neritic supra-littoral zone'),
('biomeList', 'nertic littoral zone', 'nertic littoral zone'),
('biomeList', 'marine reef biome', 'marine reef biome'),
('biomeList', 'marine coral reef biome', 'marine coral reef biome'),
('biomeList', 'marine sponge reef biome', 'marine sponge reef biome'),
('biomeList', 'marine subtidal rocky reef biome', 'marine subtidal rocky reef biome'),
('biomeList', 'marine pelagic biome', 'marine pelagic biome'),
('biomeList', 'neritic pelagic zone biome', 'neritic pelagic zone biome'),
('biomeList', 'neritic epipelagic zone biome', 'neritic epipelagic zone biome'),
('biomeList', 'neritic mesopelagic zone biome', 'neritic mesopelagic zone biome'),
('biomeList', 'neritic sea surface microlayer biome', 'neritic sea surface microlayer biome'),
('biomeList', 'oceanic pelagic zone biome', 'oceanic pelagic zone biome'),
('biomeList', 'oceanic abyssopelagic zone biome', 'oceanic abyssopelagic zone biome'),
('biomeList', 'oceanic bathypelagic zone biome', 'oceanic bathypelagic zone biome'),
('biomeList', 'oceanic benthopelagic zone biome', 'oceanic benthopelagic zone biome'),
('biomeList', 'oceanic epipelagic zone biome', 'oceanic epipelagic zone biome'),
('biomeList', 'oceanic hadal pelagic zone biome', 'oceanic hadal pelagic zone biome'),
('biomeList', 'oceanic mesopelagic zone biome', 'oceanic mesopelagic zone biome'),
('biomeList', 'oceanic sea surface microlayer biome', 'oceanic sea surface microlayer biome'),
('biomeList', 'marine salt marsh biome', 'marine salt marsh biome'),
('biomeList', 'mediterranean sea biome', 'mediterranean sea biome'),
('biomeList', 'concentration basin mediterranean sea biome', 'concentration basin mediterranean sea biome'),
('biomeList', 'dilution basin mediterranean sea biome', 'dilution basin mediterranean sea biome'),
('biomeList', 'ocean biome', 'ocean biome'),
('biomeList', 'terrestrial biome', 'terrestrial biome'),
('biomeList', 'Bailey biome', 'Bailey biome'),
('biomeList', 'Dry Domain (300)', 'Dry Domain (300)'),
('biomeList', 'Temperate Desert Division (340)', 'Temperate Desert Division (340)'),
('biomeList', 'Temperate Desert Division - Mountain Provinces (M340)', 'Temperate Desert Division - Mountain Provinces (M340)'),
('biomeList', 'Temperate Steppe Division (330)', 'Temperate Steppe Division (330)'),
('biomeList', ' Temperate Steppe Division - Mountain Provinces (M330)', ' Temperate Steppe Division - Mountain Provinces (M330)'),
('biomeList', 'Tropical/Subtropical Desert Division (320)', 'Tropical/Subtropical Desert Division (320)'),
('biomeList', 'Tropical/Subtropical Steppe Division (310)', 'Tropical/Subtropical Steppe Division (310)'),
('biomeList', 'Tropical/Subtropical Steppe Division - Mountain Provinces (M310)', 'Tropical/Subtropical Steppe Division - Mountain Provinces (M310)'),
('biomeList', 'Humid Temperate Domain (200)', 'Humid Temperate Domain (200)'),
('biomeList', 'Hot Continental Division (220)', 'Hot Continental Division (220)'),
('biomeList', 'Hot Continental Division - Mountain Provinces (M220)', 'Hot Continental Division - Mountain Provinces (M220)'),
('biomeList', 'Marine Division (240)', 'Marine Division (240)'),
('biomeList', 'Marine Division - Mountain Provinces (M240)', 'Marine Division - Mountain Provinces (M240)'),
('biomeList', 'Mediterranean Division (260)', 'Mediterranean Division (260)'),
('biomeList', 'Mediterranean Division - Mountain Provinces (M260)', 'Mediterranean Division - Mountain Provinces (M260)'),
('biomeList', 'Prairie Division (250)', 'Prairie Division (250)'),
('biomeList', 'Subtropical Division (230)', 'Subtropical Division (230)'),
('biomeList', 'Subtropical Division - Mountain Provinces (M230)', 'Subtropical Division - Mountain Provinces (M230)'),
('biomeList', 'Warm Continental Division (210)', 'Warm Continental Division (210)'),
('biomeList', 'Warm Continental Division - Mountain Provinces (M210)', 'Warm Continental Division - Mountain Provinces (M210)'),
('biomeList', 'Humid Tropical Domain (400)', 'Humid Tropical Domain (400)'),
('biomeList', 'Rainforest Division (420)', 'Rainforest Division (420)'),
('biomeList', 'Rainforest Division - Mountain Provinces (M420)', 'Rainforest Division - Mountain Provinces (M420)'),
('biomeList', 'Savanna Division (410)', 'Savanna Division (410)'),
('biomeList', 'Savanna Division - Mountain Provinces (M410)', 'Savanna Division - Mountain Provinces (M410)'),
('biomeList', 'Polar Domain (100)', 'Polar Domain (100)'),
('biomeList', 'Subarctic Division (130)', 'Subarctic Division (130)'),
('biomeList', 'Subarctic Division - Mountain Provinces (M130)', 'Subarctic Division - Mountain Provinces (M130)'),
('biomeList', 'Tundra Divsion (120)', 'Tundra Divsion (120)'),
('biomeList', 'Tundra Division - Mountain Provinces (M120)', 'Tundra Division - Mountain Provinces (M120)'),
('biomeList', 'Udvardy biome', 'Udvardy biome'),
('biomeList', 'Cold-winter (continental) deserts and semideserts', 'Cold-winter (continental) deserts and semideserts'),
('biomeList', 'Evergreen sclerophyllous forests, scrub, or woodlands', 'Evergreen sclerophyllous forests, scrub, or woodlands'),
('biomeList', 'Mixed island systems', 'Mixed island systems'),
('biomeList', 'Mixed mountain and highland systems with complex zonation', 'Mixed mountain and highland systems with complex zonation'),
('biomeList', 'Subtropical and temperate rainforests or woodlands', 'Subtropical and temperate rainforests or woodlands'),
('biomeList', 'Temperate broad-leaf forests or woodlands and subpolar deciduous thickets', 'Temperate broad-leaf forests or woodlands and subpolar deciduous thickets'),
('biomeList', 'Temperate grasslands', 'Temperate grasslands'),
('biomeList', 'Temperate needle-leaf forests or woodlands', 'Temperate needle-leaf forests or woodlands'),
('biomeList', 'Tropical dry or deciduous forests (including Monsoon forests) or woodlands', 'Tropical dry or deciduous forests (including Monsoon forests) or woodlands'),
('biomeList', 'Tropical humid forests', 'Tropical humid forests'),
('biomeList', 'Tundra communities and barren Arctic deserts', 'Tundra communities and barren Arctic deserts'),
('biomeList', 'Warm deserts and semideserts', 'Warm deserts and semideserts'),
('biomeList', 'WWF biome', 'WWF biome'),
('biomeList', 'Deserts and xeric shrubland biome', 'Deserts and xeric shrubland biome'),
('biomeList', 'Flooded grasslands and savanna biome', 'Flooded grasslands and savanna biome'),
('biomeList', 'Mangrove biome', 'Mangrove biome'),
('biomeList', 'Mediterranean forests, woodlands, and shrub biome', 'Mediterranean forests, woodlands, and shrub biome'),
('biomeList', 'Montane grasslands and shrubland biome', 'Montane grasslands and shrubland biome'),
('biomeList', 'Temperate broadleaf and mixed forest biome', 'Temperate broadleaf and mixed forest biome'),
('biomeList', 'Temperate coniferous forest biome', 'Temperate coniferous forest biome'),
('biomeList', 'Temperate grasslands, savannas, and shrubland biome', 'Temperate grasslands, savannas, and shrubland biome'),
('biomeList', 'Tropical and subtropical coniferous forest biome', 'Tropical and subtropical coniferous forest biome'),
('biomeList', 'Tropical and subtropical dry broadleaf forest biome', 'Tropical and subtropical dry broadleaf forest biome'),
('biomeList', 'Tropical and subtropical grasslands, savannas, and shrubland biome', 'Tropical and subtropical grasslands, savannas, and shrubland biome'),
('biomeList', 'Tropical and subtropical moist broadleaf forest biome', 'Tropical and subtropical moist broadleaf forest biome'),
('biomeList', 'Tundra biome', 'Tundra biome'),
  
 -- enable export
('categories', 'biomeList','exported'),

-- Sample Materials
( 'sampleMaterials', 'not known',           'Not Known' ),
( 'sampleMaterials', 'air',                 'Air'       ),
( 'sampleMaterials', 'drainage water',      'Drainage Water'),
( 'sampleMaterials', 'dust',                'Dust'),
( 'sampleMaterials', 'fecal',               'Fecal'),
( 'sampleMaterials', 'gas',                 'Gas' ),
( 'sampleMaterials', 'geysir water',        'Geysir Water' ),
( 'sampleMaterials', 'ground water',        'Groud Water' ),
( 'sampleMaterials', 'lake sediment',       'Lake Sediment' ),
( 'sampleMaterials', 'lake water',          'Lake Water' ),
( 'sampleMaterials', 'meteorite',           'Meteorite' ),
( 'sampleMaterials', 'mountain ice',        'Mountain Ice' ),
( 'sampleMaterials', 'mud',                 'Mud' ),
( 'sampleMaterials', 'ocean sediment',      'Ocean Sediment' ),
( 'sampleMaterials', 'ocean water',         'Ocean Water' ),
( 'sampleMaterials', 'organism',            'Organism'),
( 'sampleMaterials', 'physical',            'Physical'),
( 'sampleMaterials', 'river sediment',      'River Sediment'),
( 'sampleMaterials', 'river water',         'River Water'),
( 'sampleMaterials', 'rock',                'Rock'),
( 'sampleMaterials', 'sea ice',             'Sea Ice'),
( 'sampleMaterials', 'sediment pore water', 'Sediment Pore Water' ),
( 'sampleMaterials', 'soil',                'Soil' ),
( 'sampleMaterials', 'spittle',             'Spittle' ),
( 'sampleMaterials', 'stone',               'Stone' ),
( 'sampleMaterials', 'tissue',              'Tissue' ),
( 'sampleMaterials', 'vent fluid',          'Vent Fluid' ),
( 'sampleMaterials', 'whale bone',          'Whale Bone' ),

-- enable export
('categories', 'sampleMaterials','exported'),

-- Projects
('projects',  'microB3', 'Micro B3'),
('projects',  'biovel',   'Biovel'),
-- export
('categories', 'projects','exported'),


-- Weather conditions
('weatherConditions', 'Clear night','Clear night'),
('weatherConditions', 'Sunny day','Sunny day'),
('weatherConditions', 'Partly cloudy','Partly cloudy'),
('weatherConditions', 'Sunny intervals', 'Sunny intervals'),
('weatherConditions', 'Dust', 'Dust'),
('weatherConditions', 'Mist', 'Mist'),
('weatherConditions', 'Fog', 'Fog'),
('weatherConditions', 'Cloudy', 'Cloudy'),
('weatherConditions', 'Overcast', 'Overcast'),
('weatherConditions', 'Drizzle', 'Drizzle'),
('weatherConditions', 'Light rain', 'Light rain'),
('weatherConditions', 'Heavy rain', 'Heavy rain'),
('weatherConditions', 'Sleet shower', 'Sleet shower'),
('weatherConditions', 'Sleet', 'Sleet'),
('weatherConditions', 'Hail shower', 'Hail shower'),
('weatherConditions', 'Hail', 'Hail'),
('weatherConditions', 'Light snow', 'Light snow'),
('weatherConditions', 'Heavy snow', 'Heavy snow'),
('weatherConditions', 'Thunder shower', 'Thunder shower'),
('weatherConditions', 'Thunder', 'Thunder'),
('weatherConditions', 'Tropical storm', 'Tropical storm'),
('weatherConditions', 'Haze', 'Haze'),
('weatherConditions', 'No data', 'No data'),
-- export
('categories','weatherConditions','exported');



commit;