#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.

#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]

#
# CDDL HEADER END

# Copyright 2006 Sun Microsystems, Inc. All rights reserved.
# Use is subject to license terms.
#
# ident "%Z%%M% %I% %E SMI"
. /lib/svc/share/smf_include.sh

# SMF_FMRI is the name of the target service. This allows multiple instances
# to use the same script.

getproparg()
{
	  val=`svcprop -p $1 $SMF_FMRI`
      [ -n "$val" ] && echo $val
}

PGQDIR=`getproparg 'pgq/pgqdir'`
CONSUMER=`getproparg 'pgq/consumer'`
CONSUMERCONFIG=`getproparg 'pgq/consumer-config'`
TICKER=`getproparg 'pgq/ticker'`

# location of the pgqadm.py script
PGQADM="/opt/postgres/9.3.0/bin/pgqadm.py"

export PYTHONPATH="$PYTHONPATH:/opt/postgres/9.3.0/lib/python2.6/site-packages/"

# location of python
PYTHON="/opt/python/2.6.8/bin/python"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/postgres/9.3.0/lib

if [ -z $SMF_FMRI ]; then
     echo "SMF framework variables are not initialized."
     exit $SMF_EXIT_ERR
fi

if [ -z $PGDATA ]; then

     echo "postgresql/data property not set"
     exit $SMF_EXIT_ERR_CONFIG
fi

case "$1" in
'start')
    $PYTHON $PGQADM -d $PGQDIR/$TICKER ticker
    $PYTHON $PGQDIR/$CONSUMER -d $PGQDIR/$CONSUMERCONFIG
    ;;
'stop')
    $PYTHON $PGQDIR/$CONSUMER -s $PGQDIR/$CONSUMERCONFIG
    $PYTHON $PGQADM -s $PGQDIR/$TICKER
    ;;
'refresh')
    $PYTHON $PGQDIR/$CONSUMER -s $PGQDIR/$CONSUMERCONFIG
    $PYTHON $PGQADM -s $PGQDIR/$TICKER
    $PYTHON $PGQADM -d $PGQDIR/$TICKER ticker
    $PYTHON $PGQDIR/$CONSUMER -d $PGQDIR/$CONSUMERCONFIG
     ;;
\*)
     echo $"Usage: $0 {start|refresh}"
     exit 1
     ;;

esac
exit $SMF_EXIT_OK
